<?php //@todo instead of hot coding the USD currency, make it possible to use any of 'em

$registry = Zend_Registry::getInstance();

$Credits = ML_Credits::getInstance();

$signedUserInfo = $registry->get("signedUserInfo");

$this->creditInfo = $Credits->view($signedUserInfo['id']);
 
$currency = new Zend_Currency(
    array(
        'value'    => $this->creditInfo['amount']/100,
        'currency' => 'USD',
    	'display'  => Zend_Currency::USE_SHORTNAME,
    )
);
?>
<ul>
<li>Balance: <?= $this->escape($currency.' '.$currency->getShortName()) ?></li>
<li><a href="<?= $this->url(array(), "do_order") ?>">Add funds</a></li>
<li><a href="<?= $this->url(array(), "orders_1stpage") ?>">Orders history</a></li>
</ul>
