<?php 
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");

$this->headTitle("Your account balance / History");
$signedUserInfo = $registry->get("signedUserInfo");

?>
<div class="row">
<div class="span12">
<h2>Your account balance / History <?php
if ($this->paginator->getCurrentPageNumber() > 1) {
    echo ' (continuing...)';
}
?></h2>
<?php echo $this->partial("/credits/info.phtml"); ?>
<?php echo $this->render("/credits/transactions-table.phtml"); ?>
<?php
if ($this->paginator->count() > 1) {
    echo $this->paginator;
}
?>
</div>
<div class="span3">
<?php echo $this->partial("/account/menu.phtml"); ?>
</div>
</div>