<?php 
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");

$this->headTitle("Your account balance / History");
$signedUserInfo = $registry->get("signedUserInfo");

?>
<div class="yui-ge">
<div class="yui-u first">
<h2>Your account balance / History <?php if($this->paginator->getCurrentPageNumber() > 1) echo ' (continuing...)'; ?></h2>
<?= $this->partial("/credits/info.phtml"); ?>
<?= $this->render("/credits/transactions-table.phtml"); ?>
<?php if($this->paginator->count() > 1) echo $this->paginator; ?>
</div>
<div class="yui-u accountside">
<?= $this->partial("/account/menu.phtml"); ?>
</div>
</div>