<?php 
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");

$order = $this->order;

$this->headTitle("Your order #".$this->escape($order['pid']));
$signedUserInfo = $registry->get("signedUserInfo");

?>
<div class="yui-ge">
<div class="yui-u first">
<h2>Your order #<?= $this->escape(ML_Credits::printFormatedUUId($this->order['pid'])) ?></h2>
<?= $this->render("/credits/transactions-table.phtml"); ?>
<?php if(isset($this->order_coupon['hash'])): ?>
<p>Coupon redeemed for this transaction: <em><?= $this->order_coupon['hash'] ?></em>.</p>
<?php endif; ?>
<h3>Transaction information</h3>
<p>Paid for a product.</p>
</div>
<div class="yui-u accountside">
<?= $this->render("/account/menu.phtml"); ?>
</div>
</div>