<?php
// this is used in the 'orders history' and 'order' pages
$registry = Zend_Registry::getInstance();
?>
<table class="styled">
<thead><tr><th>Order Number</th><th>Date and time</th><th>Transaction</th><th>Net amount</th></tr></thead>
<tbody>
<?php
if ($this->paginator && !$this->paginator->getTotalItemCount()): ?>
<p>There is nothing here for you.</p>
<?php
else: if ($this->paginator) {
    $items = $this->paginator->getCurrentItems()->toArray();
} else {
    $items = array($this->order);
}

foreach ($items as $order):

$orderDate = new Zend_Date();
$orderDate->set($order['timestamp'], Zend_Date::ISO_8601);
$orderCurrency = new Zend_Currency(
    array(
        'value'    => $order['amount']/100,
        'currency' => 'USD',
        'display'  => Zend_Currency::USE_SHORTNAME,
    )
);

?>
<tr>
<td><?php if (!isset($this->order)): ?>
<a href="<?php echo $this->url(array("order_pid" => $order['pid']), "order"); ?>">
<?php endif; ?>
<?php echo $this->escape(Ml_Model_Credits::printFormatedUUId($order['pid'])); ?>
<?php
if (isset($this->order)):
?></a>
<?php endif; ?>
</td>
<td><?php echo $this->escape($orderDate); ?></td>
<td class="left">
<?php
switch ($order['reason_type']) {
    case "transfer" :
        $orderType = ($order['amount'] > 0) ? 'Paid' : 'Credited';
        break;
    case "redeem" :
        $orderType = "Coupon redeemed";
        break;
    default :
        $orderType = "Unknown";
        break;
}

echo $this->escape($orderType);
?>
</td>
<td class="right"><?php echo $this->escape($orderCurrency.' '.$orderCurrency->getShortName()) ?></td>
</tr>
<?php endforeach; endif; ?>
</tbody>
<?php if($this->paginator): ?>
<tfoot><tr><th>Order Number</th><th>Date and time</th><th>Transaction</th><th>Amount</th></tr></tfoot>
<?php endif; ?>
</table>
<p><small>Time zone considered: Pacific Standard Time (PST).</small></p>