<?php 
$registry = Zend_Registry::getInstance();
$userInfo = $registry->get("userInfo");
$auth = Zend_Auth::getInstance();

if ($userInfo['id'] == $auth->getIdentity()) {
    $this->headTitle("Your contacts", "PREPEND");
} else {
    $this->headTitle($this->escape($userInfo['name']) . "'s contacts", 
    "PREPEND");
}

$paginator = $this->paginator;
?>
<div class="row">
<div class="span11">
<h2><?php
if ($userInfo['id'] == $auth->getIdentity()) {
    echo 'Your';
} else {
    echo $this->escape($userInfo['name']."'s");
}
?> contacts</h2>
<?php
if ($this->paginator->getTotalItemCount()):
$contacts = $paginator->getCurrentItems()->toArray();
$date = new Zend_Date();
?>
<table id="contacts" class="contacts styled">
<thead>
<tr>
<th class="name">Name</th>
<th class="since">Since</th>
<th class="relationship">Relationship</th>
</tr>
</thead>
<tbody>
<?php
foreach ($contacts as $contact):
$date->set($contact['since'], Zend_Date::ISO_8601);
?>
<tr>
<td class="name left"><b><a href="<?php
echo $this->url(array("username" => $contact['people.alias']),
"filestream_1stpage");
?>"><?php
echo $this->escape($contact['people.name']);
?></a></b> <?php
if ($contact['has'] == $auth->getIdentity()) {
echo '<small>(that\'s you)</small>';
}
?></td>
<td><?php echo $date->get(Zend_Date::DATE_LONG); ?></td>
<td>contact
<?php if($auth->getIdentity() == $userInfo['id']): ?>
 <small>(<a href="<?php
echo $this->url(array("username" => $contact['people.alias']),
"contact_relationship");
?>">change?</a>)</small>
<?php endif; ?>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else: ?>
<p><em>No contacts.</em></p>
<?php endif; ?>
<?php
if ($this->paginator->count() > 1) {
 echo $this->paginator;
}
?>
</div>
<div class="span4">
<?php echo $this->partial("/contacts/menu.phtml"); ?>
</div>
</div>