<?php
$auth = Zend_Auth::getInstance();
$registry = Zend_Registry::getInstance();

$contacts = Ml_Model_Contacts::getInstance();

$userInfo = $registry->get("userInfo");

if ($auth->getIdentity() == $userInfo['id']) {
    $who = "you";
} else {
    $who = $userInfo['name'];
}


$contactLinks = array("list" =>
array("Contacts" =>
$this->url(array("username" => $userInfo['alias']), "contacts_1stpage")),
"reverselist" =>
array("Who counts ".$this->escape($who)." as a contact" =>
$this->url(array("username" => $userInfo['alias']), "contactsrev_1stpage")));

if ($auth->hasIdentity()) {
    if ($userInfo['id'] == $auth->getIdentity()) {
        $contactLinks['ignorelist'] = array("People you ignore" => $this->url(array("username" => $userInfo['alias']), "ignore_1stpage"));
    } else {
        $mutualContactInfo = $contacts->getInfo($auth->getIdentity(), $userInfo['id']);
    }
}
?>
<h2>Lists</h2>
<ul class="verticalmenu">
<?php

$request = Zend_Controller_Front::getInstance()->getRequest();

foreach ($contactLinks as $action => $rel) {
    if ($action == $request->getActionName()):
    ?>
    <li class="active"><a href="<?php echo current($rel) ?>"><?php echo key($rel) ?></a></li>
    <?php
    else :
    ?>
    <li><a href="<?php echo current($rel) ?>"><?php echo key($rel) ?></a></li>
    <?php
    endif;
}
?>
</ul>
<?php
if ($auth->hasIdentity() && $userInfo['id'] != $auth->getIdentity()):
?>
<h2>Your relationships</h2>
<ul id="contactrels">
<?php if(isset($mutualContactInfo['has'])): ?>
<li class="first">You count <b><?php echo $this->escape($userInfo['alias']) ?></b> as a contact.</li>
<?php else: ?>
<li class="first">You don't count <?php echo $this->escape($userInfo['alias']) ?> as a contact.</li>
<?php endif; ?>
<?php if(isset($mutualContactInfo['reverse']['has'])): ?>
<li><?php echo $this->escape($userInfo['alias']) ?> counts <b>you</b> as a contact.</li>
<?php else: ?>
<li><?php echo $this->escape($userInfo['alias']) ?> doesn't count you as a contact.</li>
<?php endif; ?>
</ul>
<?php if (!isset($mutualContactInfo['has'])): ?>
<p><a href="<?php
echo $this->url(array("username" => $userInfo['alias']),
"contact_relationship");
?>" rel="nofollow">Add <?php echo $this->escape($userInfo['alias']) ?> as a contact</a></p>
<?php else: ?>
<p><a href="<?php
echo $this->url(array("username" => $userInfo['alias']), "contact_relationship");
?>" rel="nofollow">Remove <?php echo $this->escape($userInfo['alias']) ?> from your contacts</a></p>
<?php
endif;
endif;