<?php
$auth = $this->auth;
/** @var $auth \Zend_Auth() */

$config = $this->config;
?>
&nbsp;
<div id="index-content">
<div class="container">
<div class="row">
<div class="span8">
    <ul class="inline main-page-options-list">
        <li><a href="<?= $this->url([], "user_post_new"); ?>" id="post-new-ad-button-on-main-page"><strong>Anunciar</strong></a></li>
        <li><a href="#partners"><strong>Parceiros</strong></a></li>
        <li><a href="mailto:henriquevicente@gmail.com"><strong>Contato</strong></a></li>
    </ul>
    <div id="myCarousel" class="carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item"><img src="<?= $this->staticVersion("/images/map.jpg"); ?>" /></div>
            <div class="item"><img src="<?= $this->staticVersion("/images/city-map.jpg"); ?>" /></div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
    <p id="partners" class="partners text-center visible-desktop">
        <img src="<?= $this->staticVersion("/images/partners/via-sul.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/italiana.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/eurovia.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/jac.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/jbs.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/tayo.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/toyolex.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/troller.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/caxanga.png"); ?>" />
        <img src="<?= $this->staticVersion("/images/partners/bremen.png"); ?>" /></p>
    <?php /*<div class="sharing sharing-on-index">
        <div class="fb-like" data-send="true" data-width="450" data-show-faces="true"></div>
        <a href="https://twitter.com/share" class="twitter-share-button"
           data-via="<?= $this->escape($config["services"]["twitter"]["username"]); ?>"
           data-lang="pt">Tweetar</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];
                if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";
                    fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
        </script>
    </div><!-- end of .sharing -->*/ ?>
</div>
<div class="span2">
    <form method="GET" action="<?= $this->url([], "search"); ?>" class="advanced-search hidden">
        <fieldset>
            <legend>Busca avançada</legend>
            <select name="type" id="advanced-search-type">
                <optgroup label="Veículo">
                    <option value="car">Carro</option>
                    <option value="motorcycle">Motocicleta</option>
                </optgroup>
            </select>
            <select id="advanced-search-make" name="make">
                <optgroup label="Marca">
                    <option value="">Marca</option>
                </optgroup>
            </select>
            <select id="advanced-search-model" name="model">
                <optgroup label="Modelo">
                    <option value="">Modelo</option>
                </optgroup>
            </select>
            <input type="text" name="q" />
            <div class="form-inline">
                <label>
                    <input name="transmission" value="automatic" type="checkbox">
                    <span class="label label-info has">
                        Automático
                    </span>
                </label>
                <label>
                    <input name="armor" value="1" type="checkbox">
<span class="label label-important has">
Blindado
</span>
                </label>
                <label>
                    <input name="collection" value="1" type="checkbox">
<span class="label label-inverse has-not">
        Colecionador
</span>
                </label>
                <label>
                    <input name="traction" value="4x4" type="checkbox">
<span class="label label-warning has">
4x4
</span>
                </label>
                <label>
                    <input name="handicapped" value="1" type="checkbox">
<span class="label label-handicapped has" data-rel="tooltip" data-placement="bottom"
      title="" data-original-title="para deficientes físicos">
<i class="icon-vehicle-adapted"></i><span class="hidden"> Adaptado</span>
</span>
                </label>
            </div><!-- end of .form-inline -->
            <button class="btn">Buscar</button>
        </fieldset>
    </form>
<?php
if (! $auth->hasIdentity()) {
?>
    &nbsp;
    <form class="well well-no-margin span2" enctype="application/x-www-form-urlencoded" action="<?= $this->url(array(), "login"); ?>" method="post">
        <strong>Anunciante?</strong>
        <input type="text" class="input-small" placeholder="Email" name="username" required="required">
        <input type="password" class="input-small" placeholder="Password" name="password" required="required">
        <input type="hidden" name="remember_me" value="0" />
        <label class="checkbox">
            <input type="checkbox" name="remember_me" value="1" /> Continuar conectado
        </label>
        <button type="submit" class="btn">Entrar</button>
        <p><small><a href="<?php echo $this->url(array(), "recover") ?>">Esqueceu sua senha?</a>
                <br />
                <a href="<?php echo $this->url(array(), "join"); ?>">Criar uma conta</a></small>
        </p>
    </form>
<?php
}
?>
</div>
</div>
</div><!-- end of container -->
</div><!-- end of #index-content -->
