<?php

$auth = Zend_Auth::getInstance();
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");

$this->headTitle($config['applicationname'], "SET");

$this->loginform = Ml_Model_Credential::loginForm();
?>
<div class="row">
<div class="span10" id="home-page">
<h2>Uploading and sharing your files is now easy and free. <small>Create your Plifk account now.</small></h2>
<img src="<?php echo $this->staticversion("/images/globe.jpg")?>" alt="Share your files with the world." width="170" height="141" />
<p class="home-info">
Get your www.plifk.com/username</p>
<ul id="home-buttons">
<li class="join"><p><a href="<?php echo $this->url(array(), "join")?>">Join&nbsp;us</a> in just three steps.</p></li>
<li class="tour"><p><a href="/tour">Take the tour</a>, check it out.</p></li>
<li class="about"><p>Upload up to <?php
echo $this->fileSize($config['share']['monthlyLimit'] * 1024 * 1024 * 8);
?> <em>every month.</em></p></li>
</ul>
</div>
<div class="span5">
<h2>Access your account</h2>
<?php echo $this->loginform; ?>
<p><small><a href="<?php echo $this->url(array(), "recover") ?>">Lost your username or password?</a><br />
Not already a user? <a href="<?php echo $this->url(array(), "join"); ?>">Join us</a>.</small></p>
<a href="http://www.twitter.com/plifk" class="new-window"><img src="<?php
echo $this->staticversion("/images/follow_bird_us-b.png");
?>" alt="Follow Plifk on Twitter" /></a>
</div>
</div>