<?php
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");

$order = $this->order;

$this->headTitle("Make a new call");
$signedUserInfo = $registry->get("signedUserInfo");
?>
<div class="yui3-skin-sam  yui-skin-sam" id="cal1Cont"></div>

<div class="yui-ge">
<div class="yui-u first">
<h2>Make a new call</h2>
<p>Choose which message file you want to use, the group you want to reach and the time the call should be delivered.</p>
<?= $this->call_form ?>
</div>
</div>