<?php
$this->headTitle("About Plifk", "SET");
?>
<h2>About Plifk</h2>
<p>Plifk is a web service that provides ways for people to upload and share their files on the Internet. We are interested in providing the highest quality file sharing solution we can design.</p>

<h3>Talking about design</h3>
<p>We try to be simple. We don't want to take away your focus when you do something here. We provide the means to your ends.</p>

<h3>Quality of service</h3>
<p>It's what we have in mind when we do something. We rather <em>eer</em> on the safe-side of offering less than we possibly could just to know we <b>can</b> deliver what we offer to you. So never expect from us something only possible if with loads of ads disrupting your peace of mind or anything else this bad.</p>

<?php #/about/#contact is used in the tos.phtml, also in the Vacation responder at no-reply @ Plifk's gmail ?>
<h3 id="contact">Need to talk to someone?</h3>
<p>
<ul>
<li><a href="http://support.plifk.com/" class="new-window">Community-based customer support for Plifk</a></li>
<li><a href="irc://irc.freenode.net/plifk" title="Plifk at IRC">We are on the IRC (freenode)</a> useful for the <acronym title="Application Programming Interface">API</acronym> consumer or if you already use <acronym title="Internet Relay Chat">IRC</acronym></li>
<li><a href="http://www.twitter.com/plifk" title="Plifk at Twitter" class="new-window">We are on Twitter</a> if 140 minus one minus one minus five characters is enough</li>
<li><a href="mailto:pr@plifk.com" title="Plifk's Public Relations">Public Relations</a> if you are the press (blogging, anyone?)</li>
<li><a href="mailto:partner@plifk.com" title="Plifk's Partnership Relations">Partnership inquiries</a> if you mean business</li>
<li><a href="mailto:cs@plifk.com" title="Plifk's Customer Service">Customer Service e-mail</a> for everything else</li>
</ul>

<h3>Plifk visual identity</h3>
<h4>Logo</h4>
<div class="row">
<div class="span6">
<img src="<?php echo $this->staticVersion("/images/logo-m.png") ?>" width="302" height="227" alt="Plifk's logo" />
</div>
<div class="offset2 span7">
<h5>How to use</h5>
<p>Don't do any modifications to colors or anything else such as customizing the font.<br /><br />
Plifk is <b>#000000</b> (plain black) and the symbol with out the pencil head is color <b>#29ABE2</b>.<br />
The font used for the typography is <b>Leelawadee Regular</b>. Concept by Diego Carneiro.</p>
<h5>Sizes:</h5>
<ul>
<li><a href="<?php echo $this->staticVersion("/images/logo-m.png") ?>" title="Medium Plifk logo">medium</a> (302 x 227)</li>
<li><a href="<?php echo $this->staticVersion("/images/logo-b.png") ?>" title="Large Plifk logo">large</a> (1006 x 755)</li>
<li><a href="<?php echo $this->staticVersion("/images/logo.svg") ?>" title="Plifk logo vector">scalable vector</a> (.svg)</li>
</ul>
</div>
</div>
<h4>Symbol</h4>
<div class="row">
<div class="span6">
<img src="<?php echo $this->staticVersion("/images/symbol-m.png") ?>" width="302" height="236" alt="Plifk's symbol" />
</div>
<div class="offset2 span7">
<h5>How to use</h5>
<p>This symbol should be used alone or at the left side (never the right) of the word Plifk or another phrase related.  The .svg symbol contains transparency. The visual elements in it are considered to be in front of a plain white background.</p>
<h5>Sizes:</h5>
<ul>
<li><a href="<?php echo $this->staticVersion("/images/symbol-m.png") ?>" title="Medium Plifk symbol">medium</a> (302 x 236)</li>
<li><a href="<?php echo $this->staticVersion("/images/symbol-b.png") ?>" title="Large Plifk symbol">large</a> (1006 x 788)</li>
<li><a href="<?php echo $this->staticVersion("/images/symbol.svg") ?>" title="Plifk symbol vector">scalable vector</a> (.svg; uses alpha channel for the pencil-like effect)</li>
</ul>
</div>
</div>