<?php
//help file
$this->headTitle("Help with Plifk", "SET");
?>
<h2>Help: Frequently Asked Questions</h2>
<h3>What is Plifk?</h3>
<p>Plifk is a web service that provides ways for people to upload and share their files on the Internet.</p>

<h3>How can I use it?</h3>
<p>Using Plifk is pretty straightforward. First, you need to <a href="<?php echo $this->url(array(), "join") ?>" title="Join Plifk">set up an account</a>. Then you can upload your files and they will show up on the Plifk URL you create when you sign up. Take <a href="<?php echo $this->staticUrl("/join") ?>">the tour</a> and see how simple it is to use Plifk.</p>

<h3>Where is your internal search engine?</h3>
<p>It's currently under development. It should be coming by May.</p>

<h3>Can I pay for a higher upload limit?</h3>
<p>Now we offer a free version only. We have plans to offer a paid version in the future.</p>

<h3>Can I upload copyrighted material?</h3>
<p>Unless you hold the rights to openly publish the material under the Law of the United States of America, you can not. Violators may have their accounts terminated and risks to face charges for violating the <a href="<?php echo $this->staticUrl("/tos") ?>">Terms of Service</a>.</p>

<h3>Do you offer support?</h3>
<p>We have a <a href="http://support.plifk.com/" class="new-window">community-based support</a> powered by Get Satisfaction.</p>

<h3>Can I replace a file?</h3>
<p>No. We do not support this operation<?php /*versioning*/?>.</p>

<h3>Is there any filtering?</h3>
<p>Not at this point. Search for parental control if you want more control of what can be seen on-line on your computers and how to protect your kids. But we enforce some restrictions about publishing what is know as not-safe-for-work data<?php /*(content your children doesn't want to see)*/?>.</p>

<?php
/*<h3>Why don't you have more features?</h3>
<p>Instead of offering lots of features, we offer a nice feature set. By the way, Steve Jobs has something very interesting to say <a href="http://venturehacks.com/articles/jobs-customer-development" title="Steve Jobs does customer development">about new features</a>. Our goal is to deliver the ultimate experience in sharing files you can dream of.</p>

<h3>Can I make use of your API (Application Programming Interface)?</h3>
<p>If you agree to respect the clauses of the <a href="/tos">Terms of Service</a>, you can.</p>
*/