<?php 
$this->headTitle("Privacy Policy");
?>
<h2>Privacy Policy</h2>

<p>This document is provide to inform about the policies and procedures regarding the collection, use and disclosure of personally identifiable information received from users of this Service. This document may be updated from time to time.</p>

<h3>Collection and Use of Data</h3>
<p>In order to fully interact with this Service you are required to be a registered user. By registering you have to hand us some personal information, such as your name and e-mail address. Providing additional information beyond what is required is optional, but can be powerful in giving you a better usage experience.<br /><br />

With regard to your uploaded files, you agree that we may process and make use of a limited set of meta-data as long as it does not disclose personal or private information.</p>

<h3>Cookies</h3>
<p>We may and do use HTTP cookies (a web standard digital authentication method) to authenticate your sessions. Like in many websites, you are required to accept them ir order to use our service as an authenticated user. Most browsers do store this encapsulated as a little file with some information on your hard-drive. We may make use of persistent cookies (that remains after the browser is closed) to store some information or even your entire session, in case you want your session to persist. We will not share this cookie information with no other parties.</p>

<h3>Information Sharing and Disclosure</h3>
<p>We use third parties Services in both necessary and complimentary operations including, but not limited to, for storage of data and human recognization (to block spam) and may share necessary data with them in any way that does not hurt your privacy or security of your data.<br /><br />

We may use advertising in the pages of this Service with regard to any public available data found on the website including user-generated data, but neither user e-mail addresses nor other personal information will be handed over to other parties without the previous user consentiment.</p>

<h3>Limited Warranties of Privacy</h3>
<p>We reserve the right to, in our sole discretion, comply with State regulations and collaborate with private parties disclosing data related to crimes or alleged crimes if we consider appropriate to respond to the claims or if it is necessary to protect our own property.</p>

<h3>Business Transfer</h3>
<p>We reserve the right to destroy, sell or transfer any assets which we control including your personal information if required for the continuation of this service (for example, if merging within another service or in a Service holder change event). You shall be given the opportunity to opt out of any such transfer if the entity's planned processing of your information differs materially from that set forth this Privacy Policy.</p>

<h3>Security</h3>
<p>We are very concerned about safeguarding what you provide us. We employ several different security measures for protecting your data and will publicly disclose any breach of security that can be considered a threat for you as soon as viable. Also, we do not store your passwords. When you set a new password we process it throught secure one-way encryption algorithms that are stored for later comparison using the same process everytime you provide us your password again.</p>

<h3>Links to other Sites and integration with other Services</h3>
<p>Our site contains links to other sites not related in any way with our services. Also, we may offer integration with third parties services that you can opt in. By doing so you are agreeing to comply with the third party provided Privacy Policy and you understand that they may differ materially from this one.</p>

<h3>Life of data sent to the server</h3>
<p>We may keep some useful data for whatever lenght of time we see as appropriate for future reference, even in the removal of your account. Example of affected data: shares may be kept for a time after removal for cost reduction (they are removed when there is low server activity), comments (kept forever during the life of a share unless erased), etc.</p>

<h3>Access by Children</h3>
<p>We are obligated by federal law of the United States of America not to collect personally identifiable information for children under the age of 13. Children between 13 and 18 may fully use our Services provided parent or guardian's consent. We do not knowingly collect personally identifiable information from children under 13. If you are a children, we recommend you consult a teacher, your parent or guardian if you have any questions. We can not and are not in a position to give legal advice about this subject in any way, be it about different states regulation or international access.</p>

<hr />
<p><em>Effective: October 30th, 2009</em></p>