<?php
$this->headTitle("The Plifk tour", "SET");
$registry = Zend_Registry::getInstance();
$auth = Zend_Auth::getInstance();

$config = $registry->get("config");
$monthlyLimit = $this->escape($this->fileSize($config['share']['monthlyLimit'] * 1024 * 1024 * 8));
?>
<div class="row">
<div class="span7">
<h2>Upload your files and share them with the world</h2>
<p>Count with your Plifk account to let the world see what you have to share.</p>
<p>Upload your files to your account, and let people know how to reach you here.</p>
</div>
<div class="offset3 span5">
<h2>Share your files</h2>
<div id="bandwidth">
<div class="used" style="width: 0%;"></div>
<div class="available" style="padding-left: 0%; width: 100%;">100%</div>
</div>
<small id="bandwidthinfo">Each month you can upload up to <?php echo $monthlyLimit ?>.</small>
</div>
</div>
<hr />
<div id="tour-screenshots">
<h3>Listing of the files shared by a user</h3>
<p>
<a href="http://www.plifk.com/henvic" class="new-window"><img src="<?php echo $this->staticVersion("/images/tour/stream.v1.png") ?>" alt="A user file list example" width="446" height="346" /></a>
</p>
<h3>Details about a file</h3>
<p>
<a href="http://www.plifk.com/henvic/114" class="new-window"><img src="<?php echo $this->staticVersion("/images/tour/file-details.v1.png") ?>" alt="A file page example" width="446" height="346" /></a>
</p>
<?php if(!$auth->hasIdentity()): ?><strong><a href="<?php echo $this->url(array(), "join") ?>" class="new-window">Join us</a></strong><?php endif; ?>
</div>