<?php
// @todo update the number of favorited times when the user favorites / unfavorites
$registry = Zend_Registry::getInstance();
$auth = Zend_Auth::getInstance();

$config = $registry->get('config');
$shareInfo = $registry->get('shareInfo');
$userInfo = $registry->get('userInfo');

$this->headTitle($this->escape($shareInfo['title']), "PREPEND");

$favorites = Ml_Model_Favorites::getInstance();
//$countFavorites = $favorites->count($shareInfo['id']);

$tags = Ml_Model_Tags::getInstance();

$date = new Zend_Date();
$date->set($shareInfo['uploadedTime'], Zend_Date::ISO_8601);
?>
<div class="row">
<div class="span4">
<h3><?php echo $this->escape($shareInfo['title']); ?></h3>
<a href="<?php echo $this->downloadLink($shareInfo, $userInfo); ?>" class="btn primary"><?php echo $this->escape($shareInfo['filename']); ?> (<?php echo $this->fileSize($shareInfo['fileSize'], true); ?>)</a>
<?php if ($shareInfo['short']) {
    echo "<p>" . $this->escape($shareInfo['short']) . "</p>";
}
?>
<ul class="file-info">
<li><?php echo $date->get(Zend_Date::DATE_LONG); ?></li>
<li>File-Type: <?php echo $this->escape($shareInfo['type']); ?></li>
<li><a href="<?php echo $this->url(array("username" => $userInfo['alias'],
    "share_id" => $shareInfo['id']), "favorites_1stpage"); ?>">Favorites</a></li>
</ul>
<div id="TagList">
<?php if (! empty($this->tagsList) || $auth->getIdentity() == $userInfo['id']): ?>
<h5>Tags</h5>
<ul id="thetags">
<?php echo $this->render("tags/tags.phtml") ?>
</ul>
<?php 
if ($auth->getIdentity() == $userInfo['id']) {
    $tagsForm = $tags->form();
    
    $tagsForm->setAttrib("id", "tags-form");
    
    echo $tagsForm;
}
?>
<?php endif; ?>
</div>
</div>
<div class="span7">
<h3 class="hidden">File description</h3>
<p id="description" class="somehtml">
<?php if ($shareInfo['description_filtered']): ?>
<?php echo $shareInfo['description_filtered']; ?>
<?php else: ?>
<small class="nodescr">(No file description)</small>
<?php endif; ?>
</p>
<?php echo $this->render("shares/comments.phtml"); ?>
</div>
<div class="span3 offset1">
<h3>Actions</h3>
<?php
if ($auth->getIdentity() == $shareInfo['byUid']) {
?>
<a href="<?php
echo $this->url(array("username" => $userInfo['alias'], "share_id" => $shareInfo['id']),
"editsharepage");?>" class="btn primary small" rel="nofollow">Edit info</a>
<a href="<?php
echo $this->url(array("username" => $userInfo['alias'],
"share_id" => $shareInfo['id']), "deleteshare");
?>" title="Delete this file" class="btn danger small" rel="nofollow">Delete file</a>
<?php
}
?>
<?php if ($auth->getIdentity() != $shareInfo['byUid']): ?>
<span id="shareFavorite"><?php echo $this->render("favorites/switch.phtml"); ?></span>
<?php endif; ?>
<hr class="lighten" />
<p><small>Short link: <?php echo $this->escape($this->shortLink($shareInfo['id'])); ?><br />
md5 checksum of the file: <?php echo $this->escape($shareInfo['md5']); ?></small></p>
<?php
if ($this->twitterForm) {
$this->twitterForm->getElement("tweet")->getDecorator("description")->setEscape(false);
?>
<div id="tweet-box">
<?php echo $this->twitterForm->setAttrib("id", "tweet-form") ?>
<div id="twitter-servicemsg"></div><?php //don't use <div /> ?>
</div>
<?php
}
?>
</div>
</div>
<?php echo $this->paginator; ?>