<?php if ('production' == APPLICATION_ENV) die("Nothing to see here."); ?>
<h2>Loading images for the sprites</h2>
<div style="background: url(/feed-icon-16x16.png) no-repeat;">&amp;</div>
<div style="background: url(/linkchain-bg.png) no-repeat;">&amp;</div>
<div style="background: url(/linkchain-click-bg.png) no-repeat;">&amp;</div>
<div style="background: url(/arrow-small.png) no-repeat;">&amp;</div>
<div style="background: url(/x.png) no-repeat;">&amp;</div>