<?php
$this->headTitle("Desativar conta");
$form = $this->accountForm;
?>
<div class="container">
    <div class="row">
        <?= $this->render("/account/menu.phtml"); ?>
        <div class="span6">
            <h1>Desativar conta</h1>
            <p>Você tem certeza que deseja desativar sua conta? Leia a <a href="<?= $this->staticUrl("/tos"); ?>">política de privacidade</a> para entender o que vai acontecer.</p>
            <?= $this->deleteAccountForm; ?>
        </div>
    </div>
</div>