<?php
//this is an e-mail text
$registry = Zend_Registry::getInstance();
$config = $registry->get('config');
$signedUserInfo = $registry->get("signedUserInfo");
?>
Hi <?php echo $this->escape($signedUserInfo['name']) ?> (<?php echo $this->escape($signedUserInfo['alias']) ?>).

If you want to use this e-mail address for your account
confirm it at
http://<?php echo $config['webhost'] ?><?php echo $this->url(array("confirm_uid" => $signedUserInfo['id'], "security_code" => $this->securitycode), "emailconfirm") ?>

If it was a mistake, don't open the link above.

-
<?php echo $this->escape($config['applicationname']); ?>
<?php echo $this->escape($config['webhost']);