<?php
    $this->headTitle("Sua conta");
    $form = $this->accountForm;
?>
<div class="container">
    <div class="row">
        <?= $this->render("/account/menu.phtml"); ?>
        <div class="span6">
        <?php
            if ($this->changeEmail) {
        ?>
            &nbsp;
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <p>Você requisitou uma atualização de email. Um email com um link de ativação foi enviado para o seu email. A mudança será efetuada apenas quando esta ativação for concluída.</p>
            </div>
        <?php
            }
        ?>
            <h1>Sua conta</h1>
            <form enctype="application/x-www-form-urlencoded" action="<?= $form->getAction(); ?>" class="form-stacked" method="post">
                <?php
                    echo $form->name, $form->account_type, $form->username, $form->email;
                ?>
                <div class="controls">
                    <label class="checkbox inline optional">
                        <input type="hidden" name="private_email" value="0" />
                        <input type="checkbox" name="private_email" value="1"
                            <?php
                            if($form->getElement("private_email")->getValue() == "1") {
                                echo ' checked="checked" ';
                            }
                            ?>
                            />
                        Não mostrar email publicamente
                    </label>
                </div>
                &nbsp;
                <?php
                    echo $form->website, $form->location, $form->about;
                ?>
                <div class="form-actions">
                    <input type="submit" name="submit" id="submit" value="Salvar" class="btn btn-primary btn-large" />
                </div>
                <?php
                    echo $form->hash;
                ?>
            </form>
            <a href="<?php echo $this->url(array(), "account_delete"); ?>" rel="nofollow" class="btn btn-danger btn-mini">Desativar conta</a>
        </div>
    </div>
</div>
&nbsp;
