<?php
$accountLinks = array(
"index" => array("Settings" => $this->url(array(), "account")),
"picture" => array("Picture" => $this->url(array(), "accountpicture")),
"twitter" => array("Twitter" => $this->url(array(), "accounttwitter")),
//"applications" => array("Applications" => $this->url(array(), "accountapps")),
"password" => array("Password" => $this->url(array(), "password")),
);
?>
<ul id="nav-account" class="verticalmenu">
<?php

$request = Zend_Controller_Front::getInstance()->getRequest();

foreach ($accountLinks as $action => $rel) {
    if ($action == $request->getActionName()) :
    ?>
    <li class="active"><a href="<?php echo current($rel) ?>"><?php echo key($rel) ?></a></li>
    <?php
    else :
    ?>
    <li><a href="<?php echo current($rel) ?>"><?php echo key($rel) ?></a></li>
    <?php
    endif;
}
unset($action);
unset($rel);
?>
</ul>