<?php
$currentRoute = Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName();

$menuLinks = array(
    "Configurações gerais" => "account",
    "Endereço e telefone" => "account_address",
    "Imagem do perfil" => "account_picture",
    "Redefinir sua senha" => "password",
    "Últimos acessos" => "logout"
);

?>
<div class="span3">
    &nbsp;
    <ul class="nav nav-pills nav-stacked">
        <?php
        foreach ($menuLinks as $name => $route) {
            if ($currentRoute != $route) {
                ?><li><?php
            } else {
            ?><li class="disabled"><?php
            }
    ?><a href="<?php
                echo $this->url(array(), $route);
            ?>"><i class="icon-chevron-right"></i> <?php
                echo $this->escape($name);
            ?></a>
    <?php
            echo '</li>';
        }
    ?>
    </ul>
</div>