<?php 
$registry = Zend_Registry::getInstance();
$this->headTitle("Imagem do perfil");
$signedUserInfo = $registry->get("signedUserInfo");
?>
<div class="container">
    <div class="row">
        <?= $this->render("/account/menu.phtml"); ?>
        <div class="span6">
            <h1>Imagem do perfil</h1>
            <form enctype="multipart/form-data" method="post" action="<?= $this->submitPictureForm->getAction(); ?>">
                <div class="form-actions">
                    <?php
                        if ($this->pictureLink) {
                    ?>
                    <button class="btn btn-danger" name="delete" value="Remover"><i class="icon-remove icon-white"></i> Remover</button>
                    <?php
                        }
                    ?>
                    <button id="choose-image" class="btn btn-primary"><i class="icon-file icon-white"></i> Escolher uma imagem</button>
                    <button class="btn btn-success" name="submit"><i class="icon-upload icon-white"></i> Enviar</button>
                </div>
                <input type="file" name="Image" id="upload-image" ignoreNoFile="1" />
                <?= $this->submitPictureForm->getElement("hash"); ?>
                <input type="hidden" name="MAX_FILE_SIZE" value="<?= $this->submitPictureForm->_max_picture_size; ?>" />
            </form>
            <?php
                if ($this->pictureLink) {
                    echo '<img src="', $this->pictureLink, '" class="img-polaroid" />';
                } else {
            ?><p><b>Você ainda não tem uma imagem do perfil.</b></p>
            <?php
                    $this->submitPictureForm->removeElement("delete");
                }
            ?>
        </div>
    </div>
</div>