<?php
//this is used by index.phtml
$auth = Zend_Auth::getInstance();
$registry = Zend_Registry::getInstance();

$comments = Ml_Model_Comments::getInstance();
$contacts = Ml_Model_Contacts::getInstance();

$signedUserInfo = $registry->get("signedUserInfo");

$recentComments = $comments->getRecentCommentsInAccountOf($auth->getIdentity());
$recentUploads = $contacts->getRecentUploads($auth->getIdentity());
?>
<h2>Recent activity</h2>
<?php
if (empty($recentUploads) && empty($recentComments)):
?>
<p><em>No recent activity for you.</em></p>
<?php endif; ?>
<?php if(!empty($recentUploads)): ?>
<h3>Some uploads by your contacts</h3>
<ul>
<?php
foreach ($recentUploads as $recent):
?>
<li>
<b><a href="<?php
echo $this->url(array("username" => $recent['people.alias'],
"share_id" => $recent['share.id']),
"sharepage_1stpage");
?>"><?php
echo $this->escape($recent['share.title']);
?></a></b> by <a href="<?php
echo $this->url(array("username" => $recent['people.alias']),
"filestream_1stpage");
?>"><?php echo $this->escape($recent['people.name']) ?></a>
</li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<?php if(!empty($recentComments)): ?>
<h3>Your files recently commented</h3>
<ul>
<?php
//@todo get from people_deleted also
foreach ($recentComments as $recent):
?>
<li><b><a href="<?php
echo $this->url(array("username" => $signedUserInfo['alias'],
"share_id" => $recent['share.id']),
"sharepage_1stpage")
?>"><?php
echo $this->escape($recent['share.title']); ?></a></b></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<?php
/*
 * $recentCommentsLeftElsewhere = $recent->commentsLeftBy($auth->getIdentity(), true);
 * if(!empty($recentCommentsLeftElsewhere)): ?>
<h4>Comments you've left elsewhere</h4>
<?php
foreach($recentCommentsLeftElsewhere as $recent):
?>
<h4>Your comments</h4>
<p><?php echo $this->escape($recent['comments']) ?><br />
<em>In <strong><a href="<?php
echo $this->escape($recent['people.alias'] . '/' . $recent['share.id']);
?>/"><?php
echo $this->escape($recent['share.title']);
?></a> <?php
echo $this->fileSize($recent['share.fileSize'])
?></strong></em><br />
by <?php echo $this->avatar($recent, "square") ?></p>
<?php endforeach; ?>
<?php endif; ?>
*/