<?php
$registry = Zend_Registry::getInstance();
if ($registry->isRegistered("signedUserInfo")) {
    $signedUserInfo = $registry->get("signedUserInfo");
}

$flashMessenger = $this->flashMessenger();

if (! empty($flashMessenger) ||
    (isset($signedUserInfo) && (! $signedUserInfo["avatar_info"] || ! $signedUserInfo["address"])
    )) {
?>
<div class="container">
    <div class="row">
        <div class="span12">
            <?php
            if (isset($signedUserInfo) && (! $signedUserInfo["avatar_info"] || ! $signedUserInfo["address"])) {
            ?>
                &nbsp;
                <div class="alert alert-block alert-info">
                    <p>Para poder anunciar está faltando você:<br />
                    <ul>
                        <?php
                        if (! $signedUserInfo["avatar_info"]) {
                            ?>
                            <li><a href="<?= $this->url(array(), "account_picture"); ?>">Colocar uma imagem de perfil</a></li>
                            <?php
                        }
                        if (! $signedUserInfo["address"]) {
                            ?>
                            <li><a href="<?= $this->url(array(), "account_address"); ?>">Configurar o seu endereço</a></li>
                            <?php
                        }
                        ?>
                    </ul>
                    </p>
                </div>
            <?php
            }

            foreach ($flashMessenger as $flashMessage) {
                $alertType = "";

                if (is_array($flashMessage)) {
                    switch ($flashMessage[0]) {
                        case "danger" :
                        case "error" :
                        case "info" :
                        case "success" :
                            $alertType = "alert-" . $flashMessage[0];
                    }

                    $message = $flashMessage[1];
                } else {
                    $message = $flashMessage;
                }
                ?>
                &nbsp;
                <div class="alert<?= $this->escape(" " . $alertType); ?>">
                    <a class="close" data-dismiss="alert" href="#">&times;</a>
                    <?php
                    echo $message;
                    ?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
</div>
<?php
}
?>