<?php
$registry = Zend_Registry::getInstance();

$currentRoute = Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName();

if ($registry->isRegistered("signedUserInfo")) {
    $signedUserInfo = $registry->get("signedUserInfo");
}

$persistSearchUsername = (string) filter_input(INPUT_GET, "u", FILTER_UNSAFE_RAW);

if ($this->userInfo) {
    $persistSearchUsername = ($this->userInfo["username"]);
}
?>
<div class="span7 search-area">
<form method="get" action="/search" id="search-posts-form" class="search">
    <div class="input-append search-text-append">
    <label for="search-text" class="none">Busca</label>
    <input id="search-text" type="text" maxlength="80" class="search-text" name="q" autocomplete="off"  tabindex="1" />
<button class="search-go btn btn-inverse" id="search-go" name="search-go" type="submit" tabindex="-1">Ir</button>
    </div>
<?php
$isPersistUserChecked = false;
if ($persistSearchUsername && $currentRoute == "search") {
    $isPersistUserChecked = true;
}
?>
    <button id="facets-toggle" class="facets-toggle btn visible-phone hidden" data-toggle="button"><i class="icon-filter"></i><span class="hidden"> Filtros</span></button>
<?php
if ($persistSearchUsername) {
?>
    <label for="persist-username" class="hidden">Persistir usuário</label>
    <select name="persist-username" id="persist-username" class="persist-username">
        <option value="" <?= (! $isPersistUserChecked) ? ' selected="selected"' : '' ?>>em todos usuários</option>
        <option value="<?= $this->escape($persistSearchUsername); ?>" <?= ($isPersistUserChecked) ? ' selected="selected"' : '' ?>>em <?= $this->escape($persistSearchUsername); ?></option>
    </select>
<?php
}
?>
    <div class="hidden">
        <input type="text" id="search-price-max" placeholder="R$ máximo" maxlength="16" class="span2" name="price-max" />
        <input type="text" id="search-price-min" placeholder="R$ mínimo" maxlength="16" class="span2" name="price-min" />
        <input type="text" id="search-make" name="make" placeholder="Marca" />
        <input type="text" id="search-model" name="model" placeholder="Modelo" />
        <input type="text" id="search-year" name="year" placeholder="Ano" />
        <input type="text" id="search-where" name="where" placeholder="Localização" />
        <input type="text" id="search-user" name="u" placeholder="Usuário" />
        <input type="text" id="search-transmission" name="transmission" placeholder="Câmbio" />
        <input type="text" id="search-traction" name="traction" placeholder="Tração" />
        <input type="text" id="search-handicapped" name="handicapped" placeholder="Deficiente" />
        <input type="text" id="search-collection" name="collection" placeholder="Colecionador" />
        <input type="text" id="search-armor" name="armor" placeholder="Deficiente" />
        <label class="radio">
            <input type="radio" name="type" value="" checked="checked" /> todo tipo de veículo
        </label>
        <label class="radio">
            <input type="radio" name="type" value="car" /> carro
        </label>
        <label class="radio">
            <input type="radio" name="type" value="motorcycle" /> motocicleta
        </label>
        <label class="radio">
            <input type="radio" name="type" value="boat" /> embarcação
        </label>
    </div>
    <ul id="search-tips" class="search-tips unstyled hidden">
    </ul>
</form>
</div><!-- end of .span7 -->
<div class="span2">
    <div class="btn-group navbar-controls">
<?php
if (isset($signedUserInfo)) {
?>
            <a href="<?= $this->url(array("username" => $signedUserInfo['username']), "user_stream_1stpage"); ?>"
               class="btn" tabindex="30"><?= $this->escape($signedUserInfo['username']); ?></a>
<?php
}
?>
        <button class="btn dropdown-toggle" data-toggle="dropdown" tabindex="40">
            ☰
        </button>
        <ul id="site-menu" class="site-menu dropdown-menu">
<?php
if (! isset($signedUserInfo)) {
?>
                <li>
                    <form class="navbar-login-well" enctype="application/x-www-form-urlencoded" action="<?= $this->url(array(), "login"); ?>" method="post">
                        <label for="navbar-login-username">Usuário ou email</label>
                        <input type="text" id="navbar-login-username" name="username" required="required">
                        <label for="navbar-login-password">Senha</label>
                        <input type="password" id="navbar-login-password" name="password" required="required">
                        <fieldset class="form-inline">
                            <input type="hidden" name="remember_me" value="0" />
                            <label class="checkbox">
                                <input type="checkbox" name="remember_me" value="1" /> Relembrar-me
                            </label>
                            <button type="submit" class="btn">Entrar</button>
                        </fieldset>
                    </form>
                </li>
                <li><a href="<?php echo $this->url(array(), "recover") ?>">Perdeu seu usuário ou senha?</a></li>
                <li><a href="<?php echo $this->url(array(), "join"); ?>">Cadastre-se</a></li>
<?php
}

if (isset($signedUserInfo)) {
?>
    <li>
        <a href="<?= $this->url(array(), "user_post_new"); ?>" id="post-new-ad-button">
            <i class="icon-pencil"></i> Anunciar
        </a>
    </li>
    <li class="divider-vertical"></li>
                <li>
                    <a href="<?= $this->url(array("username" => $signedUserInfo['username']), "user_stream_1stpage"); ?>">
<?= $this->picture($signedUserInfo["picture"], "/20x20"), " Meus anúncios"; ?>
                    </a>
                </li>
                <li><a href="<?= $this->url(array(), "account"); ?>"><i class="icon-wrench"></i> Minha conta</a></li>
                <li><a href="<?= $this->url(array(), "logout"); ?>" id="navbar-logout-link" rel="nofollow" class="navbar-logout-link">Sair</a></li>
<?php
}
?>
        </ul>
    </div>
</div><!-- end of .span2 -->
