<hr class="lighten" />
<div class="pagination pagination-centered">
<ul>
<?php
if (isset($this->previous)) {
?>
<li><a href="<?= $this->paginatorLink($this->previous); ?>">&larr;</a></li>
<?php
} else {
?>
<li class="prev disabled"><a href="<?= $this->paginatorLink($this->previous); ?>">&larr;</a></li>
<?php
}

$pages = $this->paginator($this->current, $this->pageCount);

while (current($pages)) {
    $page = current($pages);
    if ($this->current == $page) {
?>
<li class="active"><a href="<?= $this->paginatorLink($page); ?>"><?= $this->escape($page); ?></a></li>
<?php
    } else {
?>
<li><a href="<?= $this->paginatorLink($page); ?>"><?= $this->escape($page); ?></a></li>
<?php
    }
    if(current($pages) != next($pages) - 1 && current($pages)) {
?>
<li class="disabled"><a>…</a></li>
<?php
    }
}
if (isset($this->next)) {
?>
<li><a href="<?= $this->paginatorLink($this->next); ?>">&rarr;</a></li>
<?php
} else {
?>
<li class="next disabled"><a href="<?= $this->paginatorLink($this->next); ?>">&rarr;</a></li>
<?php
}
?>
</ul>
</div>
<?php
reset($pages);
?>