<?php
$config = $this->config;

$translatePosts = $this->translatePosts;
/** @var $translatePosts \Zend_Translate_Adapter() */

$userInfo = $this->userInfo;

$editable = $this->editable;

$types = $this->types;

$type = $this->type;
$status = $this->status;

$this->headTitle($userInfo['name'], "PREPEND");

$paginator =  $this->posts;
/** @var $paginator \Zend_Paginator() */

$escapedUserLink = $this->url(array("username" => $userInfo["username"]), "user_stream_1stpage");

$escapedUserLinkExternal = "http://" . $config["webhost"] . $config["webroot"] . $escapedUserLink;

$metaOgp = [];
$metaOgp[] = ["property" => "og:title", "content" => $userInfo["name"]];
$metaOgp[] = ["property" => "og:type", "content" => "product"];
$metaOgp[] = ["property" => "og:url", "content" => $escapedUserLinkExternal];

if ($userInfo["picture"]) {
    $metaOgp[] = [
        "property" => "og:image",
        "content" => $this->pictureLink($userInfo["picture"])
    ];
}

$this->metaOgp = $metaOgp;
?>
<div class="container">
<div class="row">
    <?= $this->render("search/facets.phtml"); ?>
    <div class="span9">
        <?= $this->render("user-post/address.phtml"); ?>
        &nbsp;
        <div class="row">
            <div class="span7">
                <span class="muted"><?php
                if (! $paginator->getTotalItemCount()) {
                    echo 'Zero';
                } else {
                    $defaultPostsPerPage = $paginator->getDefaultItemCountPerPage();
                    $page = $paginator->getCurrentPageNumber();
                    $postsInThisPage = $paginator->getCurrentItemCount();
                    $totalPosts = $paginator->getTotalItemCount();

                    $firstShowedPostItem = (($page - 1) * $defaultPostsPerPage) + 1;
                    $lastShowedPostItem = $firstShowedPostItem + $postsInThisPage - 1;

                    echo $firstShowedPostItem, '-', $lastShowedPostItem, ' de ', $this->escape($totalPosts);
                }
                ?>
                 resultados</span>
                <?= $this->render("user-stream/stock-select.phtml"); ?>
                <?php
                if ($editable) {
                ?>
                <div class="btn-group" data-toggle="buttons-checkbox">
                    <a class="btn<?= ($status == "staging") ? " active" : ""; ?>" href="<?= $escapedUserLink ?>?status=staging">pausados</a>
                    <a class="btn<?= ($status == "active") ? " active" : ""; ?>" href="<?= $escapedUserLink ?>">anunciados</a>
                    <a class="btn<?= ($status == "end") ? " active" : ""; ?>" href="<?= $escapedUserLink ?>?status=end">vendidos</a>
                </div>
                <?php
                }
                ?>
            </div>
            <div class="span2">
                <div class="btn-group pull-right" data-toggle="buttons-radio">
                    <?php
                    if ($this->postsViewStyle === "thumbnail") {
                        echo '<button id="posts-view-style-thumbnail" class="btn active"><i class="icon-th"></i></button>
<button id="posts-view-style-table" class="btn"><i class="icon-th-list"></i></button>';
                    } else {
                        echo '<button id="posts-view-style-thumbnail" class="btn"><i class="icon-th"></i></button>
<button id="posts-view-style-table" class="btn active"><i class="icon-th-list"></i></button>';
                    }
                    ?>
                </div><!-- end of .btn-group -->
            </div><!-- end of .span2 -->
        </div>
        <div class="row">
            <div class="span9">
                &nbsp;
                <div id="search-results">
                    <?php
                    echo $this->render("user-stream/table-view.phtml");
                    echo $this->render("user-stream/thumbnail-view.phtml");
                    ?>
                </div><!-- end of #user-stream-posts -->
                <div class="sharing">
                    <br />
                    <div class="fb-like pull-left" data-href="<?= $escapedUserLinkExternal; ?>"
                         data-send="true" data-layout="button_count" data-show-faces="true"></div>
                    &nbsp;
                    <a href="https://twitter.com/share" class="twitter-share-button"
                       data-url="<?= $escapedUserLinkExternal; ?>"
                       data-text="<?= $this->escape($userInfo['name']); ?>"
                       data-via="<?= $this->escape($config["services"]["twitter"]["username"]); ?>"
                       data-lang="pt">Tweetar</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];
                            if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";
                                fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
                    </script>
                </div><!-- end of .sharing -->
                <?php
                echo $this->paginationControl($paginator, null, "user-stream/pagination.phtml");
                ?>
            </div><!-- end of .span9 -->
    </div><!-- end of .span9 -->
</div><!-- end of .row -->
</div><!-- end of .row -->
</div><!-- end of .container -->