<?php
$paginator =  $this->posts;
/** @var $paginator \Zend_Paginator() */

$stock = $this->stock;

$make = $this->make;
$model = $this->model;

$makes = [];

foreach ($stock as $each) {
    if (! isset($makes[$each["make"]])) {
        $makes[$each["make"]] = [];
    }

    $makes[$each["make"]]["models"][] = $each;
}

//get the amount of vehicles per make
$makes = array_map(function ($eachMake) {
    $amount = 0;
    foreach ($eachMake["models"] as $eachModel) {
        $amount = $amount + $eachModel["amount"];
    }

    $eachMake["amount"] = $amount;

    return $eachMake;
}, $makes);
?>
<select id="stock-select" class="stock-select span2">
    <option value="">Todos veículos (<?= $this->escape($paginator->getTotalItemCount()); ?>)</option>
<?php
foreach ($makes as $eachMake => $makeInfo) {
    if ($eachMake == $make && (! $model || $model == "Outro")) {
        $selected = ' selected';
    } else {
        $selected = "";
    }
?>
    <option value="<?= $this->escape($eachMake); ?>"<?= $selected; ?>>
        ‣ <?= $this->escape($eachMake); ?> (<?= $this->escape($makeInfo["amount"]); ?>)
    </option>
<?php
    foreach ($makeInfo["models"] as $eachModel) {
        if ($eachModel["make"] != "Outro" && $eachModel["model"] != "Outro") {
            if ($eachMake == $make && $eachModel["model"] == $model) {
                $selected = ' selected';
            } else {
                $selected = "";
            }
?>
    <option value="<?= $this->escape($eachMake . ";" . $eachModel["model"]); ?>"<?= $selected; ?>>
        &nbsp; &nbsp; &nbsp;<?= $this->escape($eachModel["model"]); ?> (<?= $this->escape($eachModel["amount"]); ?>)
    </option>
<?php
        }
    }
?>
<?php
}
?>
</select>
