<?php

$userInfo = $this->userInfo;

$paginator =  $this->posts;
/** @var $paginator \Zend_Paginator() */

$posts = $paginator->getCurrentItems();

$postsPictures = $this->postsPictures;

?>
<table id="posts-table-view" class="posts-list posts-table-view table table-striped table-hover<?= ($this->postsViewStyle !== "table") ? " none" : ""; ?>">
<?php
foreach ($posts as $post) {
    $escapedPostLink = $this->url(
        array("username" => $userInfo['username'], "post_id" => $post['id']), "user_post"
    );

    $price = new Zend_Currency(array("symbol" => "R$&nbsp;"), "pt_BR");
    $price->setValue($this->escape($post["price"] / 100));
?>
<tr data-link="<?= $escapedPostLink; ?>" id="post-id-<?= $this->escape($post["id"]); ?>-row">
<td class="span1">
<?php
if (isset($postsPictures[$post["id"]][0]) && is_array($postsPictures[$post["id"]][0])) {
$picture = $postsPictures[$post["id"]][0];
?>
<?= $this->picture($picture, "/100x75"); ?>
<?php
} else {
    echo $this->picture(null, "/100x75");
}
?>
</td>
<td>
<div class="span4">
<a href="<?= $escapedPostLink; ?>">
<?= $this->escape($post["make"] . " " . $post["model"] . " " . $post["engine"] . " " . $post["name"]); ?></a>
 <span class="muted">#<?= $this->escape($post["id"]); ?></span><br />
<?= $this->escape($post["model_year"]); ?>
<?php
if ($post["km"] != "") {
?><span class="muted"> | </span><?= $this->escape($post["km"]); ?> km
<?php
}
?>
</div>
<div class="span2 special-items">
<?php
$specialItems = [];

if ($post["armor"]) {
    $specialItems[] = 'Blindado';
}

if ($post["armor"]) {
    $specialItems[] = 'Adaptado';
}

if ($post["transmission"] == 'automatic') {
    $specialItems[] = 'Automático';
}

if ($post["traction"] == '4x4') {
    $specialItems[] = '4x4';
}

if ($post["collection"]) {
    $specialItems[] = 'Colecionador';
}

$sizeOfSpecialItems = count($specialItems);

for ($counter = 0; $counter < $sizeOfSpecialItems; $counter++)
{
    echo $specialItems[$counter];

    if ($counter != $sizeOfSpecialItems - 1) {
?>
<br />
<?php
        }
    }
?>
</div>
</td>
<td class="post-listing-price">
<?= $price; ?>
<?php
if ($this->editable) {
?>
<div class="btn-group pull-right actions" data-id="<?= $this->escape($post["id"]); ?>">
<?php
if ($post["status"] != "staging") {
?>
<button class="action btn btn-mini" data-status="staging">
    <i class="icon-pause"></i>
    <span class="hidden"> pausar</span>
</button>
<?php
}

if ($post["status"] != "active") {
?>
<button class="action btn btn-mini" data-status="active">
    <i class="icon-play"></i>
    <span class="hidden"> anunciar</span>
</button>
<?php
}

if ($post["status"] != "end") {
?>
<button class="action btn btn-mini" data-status="end">
    <i class="icon-stop"></i>
    <span class="hidden"> finalizar</span>
</button>
<?php
}
?>
</div>
<?php
}
?>
</td>
</tr>
<?php
}
?>
</table>
