<?php

$userInfo = $this->userInfo;

$paginator =  $this->posts;
/** @var $paginator \Zend_Paginator() */

$posts = $paginator->getCurrentItems();
?>
<ul id="posts-thumbnail-view" class="thumbnails<?= ($this->postsViewStyle !== "thumbnail") ? " hidden" : ""; ?>">
<?php
foreach ($posts as $post) {
    $escapedPostLink = $this->url(
        array("username" => $userInfo['username'], "post_id" => $post['id']), "user_post"
    );

    $price = new Zend_Currency(array("symbol" => "R$&nbsp;"), "pt_BR");
    $price->setValue($this->escape($post["price"] / 100));
?>
<li class="span3">
<a href="<?= $escapedPostLink; ?>" class="thumbnail post-thumbnail">
<?php
    if (is_array($post["pictures"][0])) {
        $picture = $post["pictures"][0];
        echo $this->picture($picture["id"], $picture["secret"], "small.jpg");
    } else {
?>
<img src="<?= $this->staticVersion("/images/chevrolet-impala-icon-small.png"); ?>" alt="picture placeholder">
<?php
    }
?>
<p>
<?= $this->escape($post["make"] . " " . $post["model"] . " " . $post["engine"] . " " . $post["name"]); ?>
<br /><span class="post-listing-price"><?= $price; ?></span>
 <span class="muted">#<?= $this->escape($post["universal_id"]); ?></span><br />
<span class="post-listing-details">
<?= $this->escape($post["model_year"]); ?>
<?php
if ($post["km"] != "") {
?>
<span class="muted">|</span> <?= $this->escape($post["km"]); ?> km
<?php
}
?>
</span><br />
<?php
if ($post["armor"]) {
?>
<span class="label label-important">veículo blindado</span>
<?php
}

if ($post["transmission"] == 'automatic') {
?>
<span class="label label-info">câmbio automático</span>
<?php
}

if ($post["traction"] == '4x4') {
?>
<span class="label label-warning">4x4</span>
<?php
}

if ($post["model_year"] <= date("Y") - 30) {
?>
<span class="label label-inverse">colecionador</span>
<?php
}
?>
</p></a></li>
<?php
}
?>
</ul>
