<?php

$userInfo = $this->userInfo;

$paginator =  $this->posts;
/** @var $paginator \Zend_Paginator() */

$posts = $paginator->getCurrentItems();

$postsPictures = $this->postsPictures;

?>
<ul id="posts-thumbnail-view" class="posts-list posts-thumbnail-view clearfix <?= ($this->postsViewStyle !== "thumbnail") ? " none" : ""; ?>">
<?php
foreach ($posts as $post) {
    $escapedPostLink = $this->url(
        array("username" => $userInfo['username'], "post_id" => $post['id']), "user_post"
    );

    $price = new Zend_Currency(array("symbol" => "R$&nbsp;"), "pt_BR");
    $price->setValue($this->escape($post["price"] / 100));

    $hasEditableClass = "";

    if ($this->editable) {
        $hasEditableClass = ' class="editable"';
    }
?>
<li id="post-id-<?= $this->escape($post["id"]); ?>-thumbnail"<?= $hasEditableClass; ?>>
<a href="<?= $escapedPostLink; ?>">
<div class="img-place">
<?php
    if (isset($postsPictures[$post["id"]][0]) && is_array($postsPictures[$post["id"]][0])) {
        $picture = $postsPictures[$post["id"]][0];
        echo $this->picture($picture, "/400x300");
    } else {
        echo $this->picture(null, "/400x300");
    }
?>
</div>
<p>
<?= $this->escape($post["make"] . " " . $post["model"] . " " . $post["engine"] . " " . $post["name"]); ?>
<br /><span class="post-listing-price"><?= $price; ?></span>
 <span class="muted">#<?= $this->escape($post["universal_id"]); ?></span><br />
<span class="post-listing-details">
<?= $this->escape($post["model_year"]); ?>
<?php
if ($post["km"] != "") {
?>
 <span class="muted">|</span> <?= $this->escape($post["km"]); ?> km
<?php
}
?>
</span><br />
<?php
if ($post["armor"]) {
?>
<span class="label label-important">Blindado</span>
<?php
}

if ($post["handicapped"]) {
?>
<span class="label label-handicapped"><i class="icon-vehicle-adapted"></i> <span class="hidden"> Adaptado</span></span>
<?php
}

if ($post["transmission"] == 'automatic') {
?>
<span class="label label-info">Automático</span>
<?php
}

if ($post["traction"] == '4x4') {
?>
<span class="label label-warning">4x4</span>
<?php
}

if ($post["collection"]) {
?>
<span class="label label-inverse">Colecionador</span>
<?php
}

if ($this->editable) {
?>
<div class="actions" data-id="<?= $this->escape($post["id"]); ?>">
<div class="action<?= ($post["status"] == Ml_Model_Posts::STATUS_STAGING) ? " disabled" : "" ?>" data-status="staging">
<i class="icon-pause<?= ($post["status"] == Ml_Model_Posts::STATUS_STAGING) ? "" : " icon-white" ?>"></i>
<span class="hidden"> pausar</span>
</div>
<div class="action<?= ($post["status"] == Ml_Model_Posts::STATUS_ACTIVE) ? " disabled" : "" ?>" data-status="active">
<i class="icon-play<?= ($post["status"] == Ml_Model_Posts::STATUS_ACTIVE) ? "" : " icon-white" ?>"></i>
<span class="hidden"> ativar</span>
</div>
<div class="action<?= ($post["status"] == Ml_Model_Posts::STATUS_END) ? " disabled" : "" ?>" data-status="end">
<i class="icon-stop<?= ($post["status"] == Ml_Model_Posts::STATUS_END) ? "" : " icon-white" ?>"></i>
<span class="hidden"> finalizar</span>
</div>
</div><!-- end of .actions -->
<?php
}
?>
</p></a>
</li>
<?php
}
?>
</ul>
