<?php
$this->headTitle("Cancelamento da sua conta");
?>
<div class="container">
    <div class="row">
        <div class="span12">
            <h1>Cancelamento da sua conta</h1>
            <p>Ao fazer o pedido de cancelamento da conta, ela entra em modo privado.<br /><br />
            <span class="label label-info"> Informativo</span> Alguns ítens como imagens demoram algum tempo para serem escondidos.<br /><br />
            Como medida de segurança os dados continuam armazenados e podem ser requisitados conforme a <a href="<?= $this->staticUrl("/tos"); ?>">política de privacidade</a>.<br /><br />
            Em caso de remoção acidental, entre em contato conosco para saber se é possível recuperar a conta.</p>
        </div>
    </div>
</div>