<?php
$registry = Zend_Registry::getInstance();
$auth = Zend_Auth::getInstance();

$userInfo = $registry->get('userInfo');
$config = $registry->get('config');

if ($userInfo['id'] == $auth->getIdentity()) {
    $shareOf = "Your files";
} else {
    $shareOf = $userInfo['name']." files";
}

$this->headTitle($this->escape($shareOf), "PREPEND");

$this->headLink()
->appendAlternate($this->url(array("username" => $userInfo['alias']),
"userfeed"), "application/rss+xml", $shareOf." RSS feed");

$shares = $this->paginator->getCurrentItems()->toArray();
?>
<h2>Files <?php
if ($userInfo['id'] == $auth->getIdentity()):
?>you are sharing<?php
else:
?>shared by <?php
echo $this->escape($userInfo['name']);
endif;

if ($this->paginator->getCurrentPageNumber() > 1) {
    echo ' (continuing...)';
}

?></h2>
<?php if (! $this->paginator->getTotalItemCount()): ?>
<p>You aren't sharing any file.</p>
<?php else: ?>
<dl id="files">
<?php
foreach ($shares as $share):

$date = new Zend_Date();
$date->set($share['uploadedTime'], Zend_Date::ISO_8601);
?>
<dt><a href="<?php
echo $this->url(array("username" => $userInfo['alias'], "share_id" => $share['id']),
"sharepage_1stpage");
?>" title="Details about <?php
echo $this->escape($share['title']);
?>"><?php echo $this->escape($share['title']); ?></a></dt>
<dd>
<?php if ($share['short']) {
    echo "<p>" . $this->escape($share['short']) . "</p>";
}
?>
<ul>
<li><a href="<?php echo $this->downloadLink($share, $userInfo); ?>">Download <?php echo $this->escape($share['filename']); ?></a></li>
<li>Published on <?php echo $date->get(Zend_Date::DATE_LONG); ?></li>
<li>Size: <?php echo $this->fileSize($share['fileSize'], true); ?></li>
<li>Type: <?php echo $this->escape($share['type']); ?></li>
</ul>
</dd>
<?php endforeach; ?>
</dl>
<?php echo $this->paginator; ?>
<?php endif; ?>
<a href="<?php echo $this->url(array("username" => $userInfo['alias']), "userfeed")?>" title="Files of <?php echo $this->escape($userInfo['name']) ?>" class="rssicon">rss feed</a>