<?php
$userInfo = $this->userInfo;

$escapedUserLink = $this->url(array("username" => $userInfo["username"]), "user_stream_1stpage");
$address = $userInfo["address"];
?>
<address id="post-address" class="vcard post-seller-address">
<table>
<tr>
<td><a href="<?= $escapedUserLink; ?>"><?= $this->picture($userInfo["picture"], "/60x60"); ?></a></td>
<td>
<strong class="fn"><a href="<?= $escapedUserLink; ?>"><?= $this->escape($userInfo["name"]); ?></a></strong><br />
<?php
if ($userInfo["account_type"] == "retail") {
?>
<span class="street-address"><?= $this->escape($address["street_address"]); ?></span> -
<span class="neighborhood"><?= $this->escape($address["neighborhood"]); ?></span><br />
<?php
}
?>
<span class="locality"><?= $this->escape($address["locality"]); ?></span> -
<span class="region"><?= $this->escape($address["region"]); ?></span>,
<?php
if ($userInfo["account_type"] == "retail") {
?>
<span class="hidden"><span class="postal-code"><?= $this->escape($address["postal_code"]); ?></span>
<span class="country-name"><?= $this->escape($address["country_name"]); ?></span></span>
<?php
$phone = $address["phone"];

$formattedBrPhone = sprintf("(%s) %s-%s",
    mb_substr($phone, 3, 2),
    mb_substr($phone, 5, 4),
    mb_substr($phone, 9)
);
?>
<span class="tel"><a class="tel" href="tel:<?= $this->escape($phone); ?>"><?= $this->escape($formattedBrPhone); ?></a></span>
</td>
<td>
<a href="<?= $this->addressMapLink($address); ?>" id="map-link" class="map-link"
data-address="<?= $this->escape($this->addressMapLink($address, true)); ?>"><span class="hidden">mapa</span></a>
<?php
}
?>
</td>
</table>
<div id="map-modal"></div>
</address>
