<?php
$translatePosts = $this->translatePosts;
/** @var $translatePosts \Zend_Translate_Adapter() */

$post = $this->post;

$editable = $this->editable;

$availableEquipment = $this->availableEquipment;
?>
<h4 class="equipment-header">Acessórios</h4>
<dl class="post-equipments-list clearfix <?= ($editable) ? 'editable' : 'uneditable' ?>">
    <?php
    foreach ($availableEquipment as $equipmentGroupKey => $equipmentGroup) {
        ?>
        <dt><?= $this->escape($translatePosts->translate($equipmentGroupKey)); ?></dt>
        <dd>
            <ul>
                <?php
                foreach ($equipmentGroup as $eachEquipment) {
                    $equipmentKey = "equipment_" . $post["type"] . "_" . $equipmentGroupKey . "_" . $eachEquipment;
                    $hasEquipment = (is_array($post["equipment"]) && in_array($equipmentKey, $post["equipment"]));
                    ?>
                    <li>
                        <label class="checkbox <?= ($hasEquipment) ? "has" : "has-not"; ?>">
                            <input type="checkbox"
                                <?= ($hasEquipment) ? ' checked="checked"' : '' ?>
                                   name="equipment[]"
                                   value="<?= $this->escape($equipmentKey); ?>" tabindex="400"
                                >
                            <small><?= $this->escape($translatePosts->translate($equipmentKey)) ?></small>
                        </label>
                    </li>
                <?php
                }
                ?>
            </ul>
        </dd>
    <?php
    }
    unset($hasEquipment);
    ?>
</dl>
