<!-- begin of the picture management, if it exists -->
<div class="row">
    <div class="span9">
        <div id="filelist" class="table hidden">
            <table id="file-names">
                <thead>
                <tr>
                    <th>Arquivo</th>
                    <th>Tamanho</th>
                    <th>Progresso</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <div id="gallery-manager" class="post-gallery-manager hidden"></div>
        <br />
    </div><!-- end of the span9 -->
</div><!-- end of the picture management .row, if it exists -->
