<?php
$translatePosts = $this->translatePosts;
/** @var $translatePosts \Zend_Translate_Adapter() */

$postForm = $this->postForm;

$userInfo = $this->userInfo;
$post = $this->post;

$editable = $this->editable;

$availableEquipment = $this->availableEquipment;

$price = new Zend_Currency(array("symbol" => "R$&nbsp;"), "pt_BR");
$price->setValue($this->escape($post["price"] / 100));
?>
<div class="<?= ($editable) ? "post-editable" : ""; ?>" id="post-product-info"
<?= ($editable) ? 'data-rel="tooltip" title="clique para editar"': ""; ?>>
<h2 id="post-product-price">
R$&nbsp;<?= $this->escape($price->toCurrency(null, array("display" => Zend_Currency::NO_SYMBOL))); ?>
</h2>
<dl class="post-product-equipment-list dl-horizontal">
<dt><?= $this->escape($translatePosts->translate("year")); ?></dt>
<dd>
<?= $this->escape($post["model_year"]); ?>
&nbsp;</dd>
<?php
if ($post["fuel"]) {
?>
<dt><?= $this->escape($translatePosts->translate("fuel")); ?></dt>
<dd><?= $this->escape($translatePosts->translate($post["fuel"])); ?>&nbsp;</dd>
<?php
}
if ($post["km"] != "") {
?>
<dt>km</dt>
<dd><?= $this->escape($post["km"]); ?>&nbsp;</dd>
<?php
}
if ($post["transmission"]) {
?>
<dt><?= $this->escape($translatePosts->translate("transmission")); ?></dt>
<dd><?= $this->escape($translatePosts->translate($post["transmission"])); ?>&nbsp;</dd>
<?php
}
if ($post["traction"]) {
?>
<dt><?= $this->escape($translatePosts->translate("traction")); ?></dt>
<dd><?= $this->escape($translatePosts->translate($post["traction"])); ?>&nbsp;</dd>
<?php
}
if ($post["armor"]) {
?>
<dt>&nbsp;</dt>
<dd>
<span class="label label-important">Veículo blindado</span>
</dd>
<?php
}
?>
</dl>
<dl class="post-equipments-list clearfix">
<dt><?= $this->escape($translatePosts->translate("main_equipment")); ?></dt>
<dd>
<ul>
<?php
foreach ($availableEquipment as $equipment) {
    echo "<li>";
    if (is_array($post["equipment"]) && in_array($equipment, $post["equipment"])) {
        echo $this->escape($translatePosts->translate("equipment_" . $equipment));
    } else {
        echo '<del class="muted">', $this->escape($translatePosts->translate("equipment_" . $equipment)), "</del>";
    }
    echo "</li>";
}
?>
</ul>
</dd>
</dl>
</div><!-- end of #post-product-info -->
<?php
if ($editable) {
?>
<form id="post-product-info-editing-area" class="post-product-info-editing-area form-horizontal hidden" method="post">
<br />
<?php
echo
$postForm->getElement("price"),
$postForm->getElement("model_year"),
$postForm->getElement("km"),
$postForm->getElement("fuel"),
$postForm->getElement("transmission"),
$postForm->getElement("traction"),
$postForm->getElement("armor"),
'<dl class="equipment form-inline">',
$postForm->getElement("equipment")->setTranslator($this->translatePosts),
'</dl>'
;
?>
<br />
<input class="btn btn-primary" type="submit" value="Salvar equipamentos">
<button class="btn" id="post-product-info-cancel" type="button">Cancelar</button>
<?= $postForm->getElement("hash"); ?>
</form><!-- end of #post-product-info-editing-area -->
<?php
}
?>