<?php
$translatePosts = $this->translatePosts;
/** @var $translatePosts \Zend_Translate_Adapter() */

$postForm = $this->postForm;

$userInfo = $this->userInfo;
$post = $this->post;

$editable = $this->editable;

$availableEquipment = $this->availableEquipment;

$price = new Zend_Currency(array("symbol" => "R$&nbsp;"), "pt_BR");
$price->setValue($this->escape($post["price"] / 100));
?>
<div class="post-product-info <?= ($editable) ? "post-editable" : ""; ?>" id="post-product-info"
    <?= ($editable) ? 'data-rel="tooltip" title="clique para editar"': ""; ?>>
    <h2 id="post-product-price" class="post-product-info-price">
        R$&nbsp;<?= $this->escape($price->toCurrency(null, array("display" => Zend_Currency::NO_SYMBOL))); ?>
    </h2>
    <h3 class="hidden">Detalhes técnicos</h3>
    <dl class="dl-horizontal">
<dt><?= $this->escape($translatePosts->translate("year")); ?>:</dt>
<dd><?= $this->escape($post["model_year"]); ?></dd>
<dt>km:</dt>
<dd>
<?php
if ($post["km"] != "") {
?>
<?= $this->escape(number_format($post["km"], 0, ".", ".")); ?>
<?php
}
?>
&nbsp;</dd>
<dt><?= $this->escape($translatePosts->translate("fuel")); ?>:</dt>
<dd>
<?php
if ($post["fuel"]) {
?>
<?= $this->escape($translatePosts->translate($post["fuel"] . "_lowercase")); ?>
<?php
}
?>
&nbsp;</dd>
<dt><?= $this->escape($translatePosts->translate("transmission")); ?>:</dt>
<dd>
<?php
if ($post["transmission"]) {
?>
<?= $this->escape($translatePosts->translate($post["transmission"] . "_lowercase")); ?>
<?php
}
?>
&nbsp;</dd>
<dt><?= $this->escape($translatePosts->translate("traction")); ?>:</dt>
<dd>
<?php
if ($post["traction"]) {
?>
<?= $translatePosts->translate($post["traction"]); ?>
<?php
}
?>
&nbsp;</dd>
</dl>
</div><!-- end of #post-product-info -->
<?php
if ($editable) {
?>
<form id="post-product-info-editing-area" class="post-product-info-editing-area hidden" method="post">
<div class="price-input">
<?php
echo $postForm->getElement("price")
    ->removeDecorator("wrapper")
    ->removeDecorator("label")
    ->removeDecorator("htmltag")
    ->removeDecorator("description")
;
?>
</div>
<div class="year-km-inputs">
<?php
echo $postForm->getElement("model_year")
    ->removeDecorator("wrapper")
    ->removeDecorator("label")
    ->removeDecorator("htmltag")
    ->removeDecorator("description"), " ",
$postForm->getElement("km")
    ->removeDecorator("wrapper")
    ->removeDecorator("label")
    ->removeDecorator("htmltag")
    ->removeDecorator("description")
;
?>
</div>
<?php
echo $postForm->getElement("fuel")
    ->removeDecorator("wrapper")
    ->removeDecorator("htmltag")
    ->removeDecorator("description"), " ",
$postForm->getElement("transmission")
    ->removeDecorator("wrapper")
    ->removeDecorator("htmltag")
    ->removeDecorator("description"), " ",
$postForm->getElement("traction")
    ->removeDecorator("wrapper")
    ->removeDecorator("htmltag")
    ->removeDecorator("description")
;
?>
<br />
<input class="btn btn-primary" type="submit" value="Salvar">
<button class="btn" id="post-product-info-cancel" type="button">Cancelar</button>
<?= $postForm->getElement("hash")->removeDecorator('DtDdWrapper'); ?>
</form><!-- end of #post-product-info-editing-area -->
<?php
}
?>
<div class="post-product-info-others" id="post-product-info-others">
<?php
if ($post["type"] == "car" && ($post["armor"] || $editable)) {
?>
<?= ($editable) ? '<label class="label-checkbox-armor label-checkbox">' : "" ?>
<span class="label label-important<?= ($post["armor"]) ? ' has' : ' has-not' ?>">
<?php
if ($editable) {
?>
<input name="armor" type="checkbox"<?= ($post["armor"]) ? ' checked="checked"' : ''; ?> />
<?php
}
?>
Blindado
</span>
<?= ($editable) ? "</label>" : "" ?>
<?php
}

if ($post["handicapped"] || $editable) {
?>
<?= ($editable) ? '<label class="label-checkbox-handicapped label-checkbox">' : "" ?>
<span class="label label-handicapped<?= ($post["handicapped"]) ? ' has' : ' has-not' ?>"
data-rel="tooltip" data-placement="bottom" title="para deficientes físicos">
<?php
if ($editable) {
?>
<input name="handicapped" type="checkbox"<?= ($post["handicapped"]) ? ' checked="checked"' : ''; ?> />
<?php
}
?>
<i class="icon-vehicle-adapted"></i> Adaptado
</span>
<?= ($editable) ? "</label>" : "" ?>
<?php
}

if ($editable) {
    echo $this->render("user-post/post-status.phtml");
}
?>
</div>
