<?php
$translatePosts = $this->translatePosts;
/** @var $translatePosts \Zend_Translate_Adapter() */

$postForm = $this->postForm;

$userInfo = $this->userInfo;
$post = $this->post;

$editable = $this->editable;

$availableEquipment = $this->availableEquipment;
?>
<div class="post-product-info-others" id="post-product-info-others">
<?php
if ($post["type"] == "car" && ($post["armor"] || $editable)) {
?>
<?= ($editable) ? '<label class="label-checkbox-armor label-checkbox">' : "" ?>
<span class="label label-important<?= ($post["armor"]) ? ' has' : ' has-not' ?>">
<?php
if ($editable) {
?>
<input name="armor" type="checkbox"<?= ($post["armor"]) ? ' checked="checked"' : ''; ?> tabindex="120" />
<?php
}
?>
Blindado
</span>
<?= ($editable) ? "</label>" : "" ?>
<?php
}

if ($post["handicapped"] || $editable) {
?>
<?= ($editable) ? '<label class="label-checkbox-handicapped label-checkbox">' : "" ?>
<span class="label label-handicapped<?= ($post["handicapped"]) ? ' has' : ' has-not' ?>"
data-rel="tooltip" data-placement="bottom" title="para deficientes físicos">
<?php
if ($editable) {
?>
<input name="handicapped" type="checkbox"<?= ($post["handicapped"]) ? ' checked="checked"' : ''; ?> tabindex="121" />
<?php
}
?>
<i class="icon-vehicle-adapted"></i> Adaptado
</span>
<?= ($editable) ? "</label>" : "" ?>
<?php
}

if ($editable) {
    echo $this->render("user-post/post-status.phtml");
}
?>
</div>
