<?php
$post = $this->post;
?>
<br />
<form id="post-status" class="form-inline">
<label for="aaasdas" data-rel="tooltip" data-title="status do anúncio">
    <span class="hidden">status do anúncio</span><i class="icon-tasks"></i>
</label>
    <label class=" radio" for="status-staging">
        <input type="radio" name="status" id="status-staging" value="staging"
        <?php if ($post["status"] === Ml_Model_Posts::STATUS_STAGING) echo ' checked="checked"'; ?>>&nbsp;pausado
    </label>&nbsp;
    <label class=" radio" for="status-active">
        <input type="radio" name="status" id="status-active" value="active"
        <?php if ($post["status"] === Ml_Model_Posts::STATUS_ACTIVE) echo ' checked="checked"'; ?>>&nbsp;ativo
    </label>&nbsp;
    <label class=" radio" for="status-end">
        <input type="radio" name="status" id="status-end" value="end"
        <?php if ($post["status"] === Ml_Model_Posts::STATUS_END) echo ' checked="checked"'; ?>>&nbsp;finalizado
    </label>
</form>
