<?php
$post = $this->post;
$postForm = $this->postForm;
?>
<form id="post-product-name-editing-area" class="post-product-name-editing-area form-inline hidden" method="post">
    <select id="post-product-make" class="input-medium">
        <optgroup label="Marca">
            <option value="">-</option>
            <?php
            if (! empty($post["make"])) {
                ?>
                <option value="<?= $this->escape($post["make"]); ?>" selected="selected"><?= $this->escape($post["make"]); ?></option>
            <?php
            }
            ?>
        </optgroup>
    </select>
    <select id="post-product-model" class="input-medium">
        <optgroup label="Modelo">
            <option value="">-</option>
            <?php
            if (! empty($post["make"])) {
                ?>
                <option value="<?= $this->escape($post["model"]); ?>" selected="selected"><?= $this->escape($post["model"]); ?></option>
            <?php
            }
            ?>
        </optgroup>
    </select>
    <?php
    $postForm->engine->setDecorators(array('ViewHelper'));

    if ($post["type"] != Ml_Model_Posts::TYPE_CAR) {
        echo $postForm->engine;
    } else {
    ?>
        <select name="engine" id="post-product-engine" class="input-mini">
            <optgroup id="post-product-engine-optgroup-Motor" label="Motor">
                <option value="">-</option>
<?php
        for ($engineCc = 0.8; $engineCc <= 6.8; $engineCc += 0.1) {
            $engineCcFormated = number_format($engineCc, 1);
?>
<option value="<?= $this->escape($engineCcFormated); ?>"
        <?= ($engineCcFormated == $post["engine"]) ? 'selected="selected"' : "" ?>>
    <?= $this->escape($engineCcFormated); ?>
</option>
<?php
        }
?>
            </optgroup>
        </select>
<?php
    }
    ?>

    <input type="text" id="post-product-name-edit" class="post-product-name-edit input-large"
           maxlength="30" placeholder="Título" value="<?= $this->escape($post["name"]); ?>" />
    <input class="btn btn-primary" id="post-product-name-save" type="submit" value="Salvar" />
    <button class="btn" id="post-product-name-cancel" type="button">Cancelar</button>
    <select id="post-product-type" class="input-small hidden" disabled="disabled">
        <optgroup label="Veículo">
            <option value="car" <?= ($post["type"] == "car") ? 'selected="selected" ' : ''; ?>>Carro</option>
            <option value="motorcycle" <?= ($post["type"] == "motorcycle") ? 'selected="selected" ' : ''; ?>>Motocicleta</option>
            <option value="boat" <?= ($post["type"] == "boat") ? 'selected="selected" ' : ''; ?>>Embarcação</option>
        </optgroup>
    </select>
</form>
