<?php
$post = $this->post;
$postForm = $this->postForm;
?>
<form id="post-product-name-editing-area" class="post-product-name-editing-area form-inline hidden" method="post">
    <select id="post-product-make" class="input-medium">
        <optgroup label="Marca">
            <option value="">-</option>
            <?php
            if (! empty($post["make"])) {
                ?>
                <option value="<?= $this->escape($post["make"]); ?>" selected="selected"><?= $this->escape($post["make"]); ?></option>
            <?php
            }
            ?>
        </optgroup>
    </select>
    <select id="post-product-model" class="input-medium">
        <optgroup label="Modelo">
            <option value="">-</option>
            <?php
            if (! empty($post["make"])) {
                ?>
                <option value="<?= $this->escape($post["model"]); ?>" selected="selected"><?= $this->escape($post["model"]); ?></option>
            <?php
            }
            ?>
        </optgroup>
    </select>
    <?php
    $postForm->engine->setDecorators(array('ViewHelper'));
    echo $postForm->engine;
    ?>

    <input type="text" id="post-product-name-edit" class="post-product-name-edit input-large"
           maxlength="30" placeholder="Título" value="<?= $this->escape($post["name"]); ?>" />
    <input class="btn btn-primary" id="post-product-name-save" type="submit" value="Salvar" />
    <button class="btn" id="post-product-name-cancel" type="button">Cancelar</button>
</form>
