<?php
$this->headTitle("Login screen");
?>
<div class="row">
<div class="span10">
<?php if ($this->errorlogin): ?>
<h2>Duh! Something is wrong!</h2>
<img src="<?php echo $this->staticVersion("/illustrations/girl-showing-tongue.jpg"); ?>" alt="" width="424" height="283" />
<?php else: ?>
<h2>Come in! We are waiting for you!</h2>
<img src="<?php echo $this->staticVersion("/illustrations/girl-inviting.jpg"); ?>" alt="" width="424" height="283" />
<?php endif; ?>
</div>
<div class="span5">
<h2>Access your account</h2>
<?php echo $this->loginform; ?>
<p><small><a href="<?php echo $this->url(array(), "recover") ?>">Lost your username or password?</a><br />
Not already a user? <a href="<?php echo $this->url(array(), "join") ?>">Join us</a>.</small></p>
</div>
</div>