<? // login/index.phtml
$this->headTitle("Login screen");

?>
<div class="yui-g">
<div class="yui-u first">
<h2>Access your account</h2>
<?php /*<p><strong>Not yet a member? <a href="/join/">Join us</a> today.</strong></p>*/?>
<?= $this->loginform ?>
<p><small><a href="<?= $this->url(array(), "recover") ?>">Lost your username or password?</a><br />
<b>Not already a user? <a href="<?= $this->url(array(), "join") ?>">Join us</a>.</b></small></p>
</div>
<div class="yui-u">
<?php if($this->errorlogin): ?>
<h2>Duh! Something is wrong!</h2>
<img src="<?= $this->staticversion("/illustrations/girl-showing-tongue.jpg") ?>" alt="" width="424" height="283" />
<?php else: ?>
<h2>Come in! We are waiting for you!</h2>
<img src="<?= $this->staticversion("/illustrations/girl-inviting.jpg") ?>" alt="" width="424" height="283" />
<?php endif; ?>
</div>
</div>