<?php
$this->headTitle("API | Edit Key Information");
?>
<h2><a href="<?php echo $this->url(array(), "apikeys") ?>">Your API keys</a></h2>
<?php
$consumer = $this->consumerData;
?>
<h3>Your API Key details</h3>
<p><strong>Key: <?php echo $this->escape($consumer['consumer_key']) ?></strong><br />
<strong>Secret: <?php echo $this->escape($consumer['consumer_secret']) ?></strong></p>
<?php echo $this->apiKeyForm ?>
<p><strong><a href="<?php
echo $this->url(array("api_key" => $consumer['consumer_key']),
"api_key_delete")
?>">Delete this API key</a>.</strong></p>
<p>Or see all the <a href="<?php
echo $this->url(array(), "apikeys") ?>">API keys</a> you have.</p>