<?php
$this->headTitle("API | Your Keys");
?>
<h2>Your API keys</h2>
<p>Some methods of the Plifk API can only be used by applications registered with the Plifk service. Developers can require and see the API keys for your applications here.</p>
<?php if(!is_array($this->listConsumers) || empty($this->listConsumers)): ?>
<p>Currently you don't have any application key registered.</p>
<?php else: ?>
<dl>
<?php
foreach ($this->listConsumers as $consumer):
?>
<dt><a href="<?php
echo $this->url(array("api_key" => $consumer['consumer_key']), "api_key");
?>"><?php
echo $this->escape($consumer['application_title']);
?></a></dt>
<dd>
<ul>
<li><strong>Key:</strong> <?php echo $this->escape($consumer['consumer_key']); ?></li>
<li><strong>Secret:</strong> <?php echo $this->escape($consumer['consumer_secret']); ?></li>
<li><strong>Issued:</strong> <?php
$date = new Zend_Date(); $date->set($consumer['issue_date'], Zend_Date::ISO_8601);
echo $date->get(Zend_Date::DATE_LONG); 
?></li>
<li><strong>Application URI:</strong> <i><?php
echo $this->escape($consumer['application_uri']); 
?></i></li>
<li><strong>Description:</strong> <i><?php echo $this->escape($consumer['application_descr']); ?></i></li>
</ul>
</dd>
<?php endforeach; ?>
</dl>
<?php endif; ?>
<p><strong><a href="<?php
echo $this->url(array(), "apply_api_key") ?>">Apply for a new API key</a></strong></p>