<?php
$registry = Zend_Registry::getInstance();
$userInfo = $registry->get('userInfo');
$shareInfo = $registry->get('shareInfo');
$commentInfo = $registry->get("commentInfo");

$this->headTitle("Delete comment");
?>
<h2><a href="<?php
echo $this->url(array("username" => $userInfo['alias'],
"share_id" => $shareInfo['id'], "comment_id" => $commentInfo['id']),
"commentpermalink");
?>">Comment on <?php echo $this->escape($shareInfo['title']) ?></a></h2>
<h3>Are you sure you want to delete this comment?</h3>
<div id="commentPreview">
<p class="somehtml"><?php echo $this->comment['comments_filtered']; ?></p>
</div>
<?php echo $this->form;