<?php
$registry = Zend_Registry::getInstance();

$userInfo = $registry->get('userInfo');
$shareInfo = $registry->get('shareInfo');
$commentInfo = $registry->get("commentInfo");

$this->commentForm
->getElement("commentMsg")
->getDecorator("description")->setEscape(false);

$this->headTitle("Edit comment");
?>
<h2><a href="<?php
echo $this->url(array("username" => $userInfo['alias'],
"share_id" => $shareInfo['id'],
"comment_id" => $commentInfo['id']),
"commentpermalink");
?>">Comment on <?php echo $this->escape($shareInfo['title']) ?></a></h2>
<?php if (isset($this->commentPreview)):
$purifier = Ml_HtmlPurifier::getInstance();
?>
<h3>Preview your comment</h3>
<div id="commentPreview">
<p class="somehtml"><?php echo $purifier->purify($this->commentPreview); ?></p>
</div>
<?php endif; ?>
<?php echo $this->commentForm;