<?php
$postForm = $this->postForm;

$postForm->type->setDecorators(array('ViewHelper'));

$postForm->engine->setDecorators(array('ViewHelper'));

$postForm->model_year->setDecorators(array('ViewHelper'));

$postForm->price->setDecorators(array('ViewHelper', 'Addon'));

$postForm->km->setDecorators(array('ViewHelper', 'Addon'));

$postForm->fuel->setDecorators(array('ViewHelper', 'Addon'));

$postForm->transmission->setDecorators(array('ViewHelper', 'Addon'));

$postFormErrors = $postForm->getErrors();
?>
<div id="post-product-new-modal" class="modal <?= ($this->isModal) ? " hide fade" : ""; ?>" tabindex="-1" role="dialog">
    <div class="modal-header">
<?php
if ($this->isModal) {
?>
            <button type="button" class="close" data-dismiss="modal"><span class="hidden">close </span>×</button>
<?php
}
?>
        <h3>Publicar novo anúncio</h3>
    </div>
    <div class="modal-body">
        <form id="post-product-new" method="post" action="<?= $this->url(array(), "user_post_new"); ?>"
              class="form-inline">
            <table class="table">
                <tr>
                    <td><label for="post-product-type-new">Veículo</label></td>
                    <td><?= $postForm->type; ?></td>
                </tr>
                <tr>
                    <td><label for="post-product-make-new">Marca</label></td>
                    <td>
                        <select id="post-product-make-new" class="input-medium" name="make">
                            <optgroup label="Marca">
                                <option value="">-</option>
                            </optgroup>
                        </select>
                        <?php
                        if (!empty($postFormErrors["make"])) {
                            ?>
                            <span class="help-inline">Value is required and can't be empty</span>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td><label for="post-product-model-new">Modelo</label></td>
                    <td>
                        <select id="post-product-model-new" class="input-medium" name="model">
                            <optgroup label="Modelo">
                                <option value="">-</option>
                            </optgroup>
                        </select>
                        <?php
                        if (!empty($postFormErrors["model"])) {
                            ?>
                            <span class="help-inline">Value is required and can't be empty</span>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td>Motor</td>
                    <td>
                        <?= $postForm->engine; ?>
                        <select name="engine" id="post-product-engine-Car" class="input-mini">
                            <optgroup label="Motor">
                                <option value="">-</option>
                                <?php
                                for ($engineCc = 0.8; $engineCc <= 6.8; $engineCc += 0.1) {
                                    $engineCcFormated = number_format($engineCc, 1);
                                ?>
                                <option value="<?= $this->escape($engineCcFormated); ?>">
                                    <?= $this->escape($engineCcFormated); ?>
                                </option>
                                <?php
                                }
                                ?>
                            </optgroup>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>Ano do modelo</td>
                    <td><?= $postForm->model_year; ?></td>
                </tr>
                <tr>
                    <td>Preço</td>
                    <td><?= $postForm->price; ?></td>
                </tr>
                <tr>
                    <td>Quilometragem</td>
                    <td><?= $postForm->km; ?></td>
                </tr>
                <tr>
                    <td>Combustível</td>
                    <td><?= $postForm->fuel; ?></td>
                </tr>
                <tr>
                    <td>Transmissão</td>
                    <td><?= $postForm->transmission; ?></td>
                </tr>
            </table>

            <?php
            $postForm->engine->setDecorators(array('ViewHelper', 'Label'));
            echo $postForm->hash;
            ?>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <button class="btn btn-primary" type="submit" id="post-product-new-next">
            <i class="icon-forward icon-white"></i> Prosseguir
        </button>
    </div>
</div>
