<div id="post-product-open-modal"
     class="modal <?= ($this->isModal) ? " hide fade" : ""; ?>" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span class="hidden">close </span>×</button>
        <h3>Localizar veículo</h3>
    </div>
    <div class="modal-body">
        <form class="form-horizontal" id="open-vehicle">
            <div class="control-group">
                <label class="control-label" for="input-open-vehicle">ID do veículo</label>
                <div class="controls">
                    <input type="text" id="input-open-vehicle" name="id">
                    <button type="submit" class="btn">Abrir</button>
                </div>
            </div>
        </form>
    </div>
</div>