<?php
$auth = Zend_Auth::getInstance(); 
$registry = Zend_Registry::getInstance();
$userInfo = $registry->get('userInfo');
if ($auth->getIdentity() != $userInfo['id']) {
    $title = "Tags used by ".$this->escape($userInfo['name']);
} else {
    $title = "Tags you use";
}

$this->headTitle($title, "PREPEND");

?>
<h2><?php echo $title ?></h2>
<?php
$tagsNum = sizeof($this->taglist);
if ($tagsNum == 0) :
?>
<p>There is no tags here.</p>
<?php else : ?>
<ul>
<?php
$timesUsedByAllTags = array_sum(array_values($this->taglist));

foreach ($this->taglist as $tag => $timesUsed):

if (1.5 * $timesUsedByAllTags / $tagsNum < $timesUsed) {
    $highlightTag = true;
} else {
    $highlightTag = false;
}
?>
<?php
if ($highlightTag) {
    echo "<strong>";
}
?>
<li><a href="<?php
echo $this->url(array("username" => $userInfo['alias'],
"tag" => $tag), "tagpage_1stpage");
?>" rel="tag"><?php echo $this->escape($tag); ?></a></li>
<?php
if ($highlightTag) {
    echo "</strong>"; 
}
?>
<?php
endforeach;
unset($highlightTag);
?>
</ul>
Total of <?php echo $tagsNum; ?> tags.
<?php
endif;