<? // logout/index.phtml
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");
$this->headTitle("Sign out");
$signedUserInfo = $registry->get("signedUserInfo");
?>
<div class="yui-gc">
<div class="yui-u first">
<?php if(isset($_GET['please']) || $registry->isRegistered("pleaseSignout")):?>
<h2>Logout first</h2>
<p>Either an action you have tried to perform or a section you have tried to access can not be performed as a signed in user to the account <em><?= $this->escape($signedUserInfo['name']) ?> (<?= $this->escape($signedUserInfo['alias']) ?>)</em>. Please, sign out and try again.</p>
<?php endif; ?>
<h2>Sign out of <?= $this->escape($config->applicationname) ?></h2>
<p>If you ever forget to logout from a public computer, sign out all other sessions from this page.</p>
<table>
<thead>Currently logged in from</thead>
<th>
<td>Session</td>
<td>Last IP</td>
<td>Last time connected</td>
<td>Logged in</td>
</th>
<tr>
<td>1</td>
<td>23423</td>
<td>234234</td>
<td>2342342</td>
</tr>
</table>
<p>This computer is using IP address <?= $this->escape($_SERVER['REMOTE_ADDR']) ?>.
<?php
if($this->remote_logout_done):
?>
<p><strong>Your other sessions have been signed out!</strong></p>
<?php endif; ?>
<?= $this->logoutForm ?>
</div>
</div>