<?php
//this is an e-mail text
$registry = Zend_Registry::getInstance();
$config = $registry->get('config');
?>
Hi <?php echo $this->escape($this->recoverUser['name']); ?>!

Your username at Plifk is <?php echo $this->escape($this->recoverUser['alias']); ?>.

If you remember your password you can login right now at
<?php

if ($config['ssl']) {
    echo "https://" . $config['webhostssl'];
} else {
    echo "http://" . $config['webhost'];
}

echo $this->url(array(), "login");
?>

If you need to set a new password go to
<?php

if ($config['ssl']) {
    echo "https://" . $config['webhostssl'];
} else {
    echo "http://" . $config['webhost'];
}

echo $this->url(array("confirm_uid" => $this->recoverUser['id'],
"security_code" => $this->securitycode), "password_unsigned");
?>

-
<?php echo $this->escape($config['applicationname']); ?>
<?php echo $this->escape($config['webhost']);