<?php
$this->headTitle("Set the password for ".$this->escape($this->userInfoDataForPasswordChange['name'])." (".$this->escape($this->userInfoDataForPasswordChange['alias']).")");
$auth = Zend_Auth::getInstance();
$params = $this->request->getParams();
if($auth->hasIdentity()):
?>
<div class="yui-ge">
<div class="yui-u first">
<?php endif; ?>
<?php
if(isset($this->passwordReset)): ?>
<h2>The password for the account <em><?= $this->escape($this->userInfoDataForPasswordChange['name'])." (".$this->escape($this->userInfoDataForPasswordChange['alias']);?>)</em> has been updated</h2>
<?php if($auth->hasIdentity()): ?>
<p>From now on you will have to use this password to log in this account.</p>
<?php else: ?>
<p>Now you can <a href="<?= $this->url(array(), "login") ?>" rel="nofollow">log in</a> with it.</p>
<?php endif; ?>
<?php else: ?>
<h2>Set the password for <?= $this->escape($this->userInfoDataForPasswordChange['name']); ?> (<?= $this->escape($this->userInfoDataForPasswordChange['alias']) ?>)</h2>
<?php
$this->passwordForm->getElement("password")->getDecorator("description")->setEscape(false);
?>
<?= $this->passwordForm ?>
<?php endif; ?>
<?php if($auth->hasIdentity() && (!isset($params['confirm_uid']) || $params['confirm_uid'] == $auth->getIdentity())): ?>
</div>
<div class="yui-u accountside">
<?= $this->partial("/account/menu.phtml"); ?>
</div>
</div>
<?php endif; ?>