<?php
$this->headTitle("Your password");
$auth = Zend_Auth::getInstance();
$params = $this->request->getParams();
if($auth->hasIdentity()):
?>
<div class="yui-ge">
<div class="yui-u first">
<?php endif; ?>
<?php
if(isset($this->passwordReset)): ?>
<h2>Your password is updated</h2>
<?php if($auth->hasIdentity()): ?>
<p>From now on you will have to use it to log in.</p>
<?php else: ?>
<p>Now you can <a href="<?= $this->url(array(), "login") ?>" rel="nofollow">log in</a> with it.</p>
<?php endif; ?>
<?php else: ?>
<h2>Change your password</h2>
<?php
$this->passwordForm->getElement("password")->getDecorator("description")->setEscape(false);
?>
<?= $this->passwordForm ?>
<?php endif; ?>
<?php if($auth->hasIdentity() && (!isset($params['confirm_uid']) || $params['confirm_uid'] == $auth->getIdentity())): ?>
</div>
<div class="yui-u accountside">
<?= $this->partial("/account/menu.phtml"); ?>
</div>
</div>
<?php endif; ?>