<?php
$this->headTitle("Não foi possível recuperar a sua senha");
?>
&nbsp;
<div class="container">
    <div class="row">
        <div class="span12">
            <h1>Não foi possível recuperar a sua senha</h1>
            <p>Provavelmente você já a recuperou ou esse link de confirmação expirou.<br /><br />
                <a href="<?php echo $this->url(array(), "recover"); ?>" class="btn">Tentar recuperar a senha novamente</a></p>
        </div>
    </div><!-- end of .row -->
</div><!-- end of .container -->