<?php

$auth = Zend_Auth::getInstance();
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");

$profile = Ml_Model_Profile::getInstance();
$contacts = Ml_Model_Contacts::getInstance();

$userInfo = $registry->get("userInfo");

$this->headTitle($config['applicationname'] . ": " . $this->escape($userInfo['name']), "SET");

$profileInfo = $profile->getById($userInfo['id']);

?>
<div class="yui-g">
<h2>About <?php echo $this->escape($userInfo['name']); ?></h2>
<ul>
<?php
if ($auth->hasIdentity() && $auth->getIdentity() != $userInfo['id']) {
    $contactInfo = $contacts->getRelationship($auth->getIdentity(), $userInfo['id']);
    
    if (isset($contactInfo['id'])) {
        echo '<li><b>You count ' . $this->escape($userInfo['alias']) .
        '</b> as a contact (<a href="' . $this->url(array("username" => $userInfo['alias']),
        "contact_relationship").'" rel="nofollow">change?</a>).</li>' . "\n";
    } else {
        $ignore = Ml_Model_Ignore::getInstance();
        $ignoreStatus = $ignore->status($auth->getIdentity(), $userInfo['id']);
        
        if (isset($ignoreStatus['ignore'])) {
            echo '<li><b>You have blocked this user.</b> <a href="' .
        $this->url(array("username" => $userInfo['alias']), "contactRelationshipIgnore") .
        '" rel="nofollow">Change?</a></li>' . "\n";
        }
        
        echo '<li><b><a href="' . $this->url(array("username" => $userInfo['alias']),
        "contact_relationship") . '" rel="nofollow">Add ' .
        $this->escape($userInfo['alias']) . ' as a contact</a></b></li>';
    }
    
    if (is_array($contactInfo['reverse'])) {
        echo "<li>" . $this->escape($userInfo['alias']) . " counts <b>you</b> as a contact.</li>";
    }
}
?>
<?php
if (! empty($profileInfo['website'])):
?><li><strong>Website:</strong> <a href="<?php
echo $this->escape($profileInfo['website']);
?>"><?php
echo $this->escape($profileInfo['website']);
?></a></li><?php
endif;
if (! empty($profileInfo['location'])):
?><li><strong>Location:</strong> <?php echo $this->escape($profileInfo['location']) ?></li><?php endif; ?>
</ul>
<p id="profile_desc" class="somehtml">
<?php
if ($profileInfo['about_filtered']):
echo $profileInfo['about_filtered'];
else:
?>
<small class="nodescr">(about not available)</small>
<?php endif; ?>
</p>
<?php $avatar = $this->avatarprofile($userInfo); if($avatar): ?>
<h3>User image</h3>
<?php
echo $avatar;
endif;

if ($auth->hasIdentity() && $auth->getIdentity() != $userInfo['id'] &&
(! isset($ignoreStatus) || ! is_array($ignoreStatus))):
?>
<p class="longbreak"><small><a href="<?php
echo $this->url(array("username" => $userInfo['alias']), "contactRelationshipIgnore");
?>" rel="nofollow">Block this user?</a></small></p>
<?php endif;?>
</div>