<?php
$facetsQuery = $this->facetsQuery;

$facets = (isset($facetsQuery["facets"])) ? $facetsQuery["facets"] : null;

$translatePosts = $this->translatePosts;
/** @var $translatePosts \Zend_Translate_Adapter() */

$searchLink = $this->url(array(), "search");
?>
<div class="aside-similar-offers search-facets hidden-phone">
    <dl>
        <dt>Tipo</dt>
        <dd>
            <ul>
                <?php
                if ($facets["type"]["terms"]) {
                    foreach ($facets["type"]["terms"] as $term) {
                        if (! isset($term["term"]) || ! is_string($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                            continue;
                        }
                        ?>
                        <li><a href="<?= $searchLink ?>?q=*&amp;type=<?= urlencode($term["term"]); ?>"><?= $this->escape($translatePosts->translate($term["term"] . "_lowercase")); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                    }
                }
                ?>
            </ul>
        </dd>
        <dt><?= $this->escape($translatePosts->translate("make")); ?></dt>
        <dd>
            <ul>
                <?php
                if (isset($facets["make"]["terms"])) {
                    foreach ($facets["make"]["terms"] as $term) {
                        if (! isset($term["term"]) || ! is_string($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                            continue;
                        }
                        ?>
                        <li><a href="<?= $searchLink ?>?q=*&amp;make=<?= urlencode($term["term"]); ?>"><?= $this->escape($term["term"]); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                    }
                    ?>
                    <?php
                }
                ?>
            </ul>
        </dd>
        <dt><?= $this->escape($translatePosts->translate("model")); ?></dt>
        <dd>
            <ul>
                <?php
                if (isset($facets["model"]["terms"])) {
                    foreach ($facets["model"]["terms"] as $term) {
                        if (! isset($term["term"]) || ! is_string($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                            continue;
                        }
                        ?>
                        <li><a href="<?= $searchLink ?>?q=*&amp;model=<?= urlencode($term["term"]); ?>"><?= $this->escape($term["term"]); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                    }
                    ?>
                    <?php
                }
                ?>
            </ul>
        </dd>
        <dt>Ano do modelo</dt>
        <dd>
            <ul>
                <?php
                if (isset($facets["year"]["terms"])) {
                    foreach ($facets["year"]["terms"] as $term) {
                        if (! isset($term["term"]) || ! is_int($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                            continue;
                        }
                        ?>
                        <li><a href="<?= $searchLink ?>?q=*&amp;year=<?= urlencode($term["term"]); ?>"><?= $this->escape($term["term"]); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                    }
                    ?>
                    <?php
                }
                ?>
            </ul>
        </dd>
        <dt>Preço</dt>
        <dd>
            <ul>
                <?php
                if (isset($facets["price"]["ranges"])) {
                    foreach ($facets["price"]["ranges"] as $term) {
                        if (! isset($term["count"]) || ! is_int($term["count"]) || $term["count"] === 0) {
                            continue;
                        }

                        if (! isset($term["from"]) && ! isset($term["to"])) {
                            continue;
                        }

                        $priceRangeLinkPartEscaped = "";

                        if (isset($term["to"])) {
                            $priceRangeLinkPartEscaped .= "&amp;price-max=" . urlencode($term["to"]);

                            $priceMax = new Zend_Currency(array("symbol" => "R$&nbsp;"), "pt_BR");
                            $priceMax->setValue($this->escape($term["to"] / 100));
                        }

                        if (isset($term["from"]) && $term["from"] !== 0) {
                            $priceRangeLinkPartEscaped .= "&amp;price-min=" . urlencode($term["from"]);

                            $priceMin = new Zend_Currency(array("symbol" => "R$&nbsp;"), "pt_BR");
                            $priceMin->setValue($this->escape($term["from"] / 100));
                        }

                        $priceStringEscaped = "";

                        if (isset($priceMin) && isset($priceMax)) {
                            $priceStringEscaped = $priceMin . " a " . $priceMax;
                        } else if (isset($priceMax)) {
                            $priceStringEscaped = "até " . $priceMax;
                        } else if (isset($priceMin)) {
                            $priceStringEscaped = $priceMin . " +";
                        }
                        ?>
                        <li><a href="<?= $searchLink ?>?q=*<?= $priceRangeLinkPartEscaped; ?>"><?= $priceStringEscaped; ?></a> (<?= $this->escape($term["total_count"]); ?>)</li>
                        <?php
                        unset($priceRangeLinkPartEscaped);
                        unset($priceMax);
                        unset($priceMin);
                        unset($priceStringEscaped);
                    }
                    ?>
                    <?php
                }
                ?>
            </ul>
        </dd>
        <dt>Localização</dt>
        <dd>
            <ul>
                <?php
                if (isset($facets["where"]["terms"])) {
                    foreach ($facets["where"]["terms"] as $term) {
                        if (! isset($term["term"]) || ! is_string($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                            continue;
                        }
                        ?>
                        <li><a href="<?= $searchLink ?>?q=*&amp;where=<?= urlencode($term["term"]); ?>"><?= $this->escape($term["term"]); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                    }
                    ?>
                    <?php
                }
                ?>
            </ul>
        </dd>
    </dl>
</div>