<?php
$facetsQuery = $this->facetsQuery;

$facets = (isset($facetsQuery["facets"])) ? $facetsQuery["facets"] : null;

$translatePosts = $this->translatePosts;
/** @var $translatePosts \Zend_Translate_Adapter() */

$searchLink = $this->url(array(), "search");
?>
<div class="span2">
    <div class="aside-similar-offers search-facets hidden-phone">
        <dl>
            <dt>Tipo</dt>
            <dd>
                <ul>
                    <?php
                    if ($facets["type"]["terms"]) {
                        foreach ($facets["type"]["terms"] as $term) {
                            if (! isset($term["term"]) || ! is_string($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                                continue;
                            }
                            ?>
                            <li><a href="<?= $searchLink ?>?q=*&amp;type=<?= urlencode($term["term"]); ?>"><?= $this->escape($translatePosts->translate($term["term"] . "_lowercase")); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                        }
                    }
                    ?>
                </ul>
            </dd>
            <dt><?= $this->escape($translatePosts->translate("make")); ?></dt>
            <dd>
                <ul>
                    <?php
                    if (isset($facets["make"]["terms"])) {
                        foreach ($facets["make"]["terms"] as $term) {
                            if (! isset($term["term"]) || ! is_string($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                                continue;
                            }
                            ?>
                            <li><a href="<?= $searchLink ?>?q=*&amp;make=<?= urlencode($term["term"]); ?>"><?= $this->escape($term["term"]); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                        }
                        ?>
                    <?php
                    }
                    ?>
                </ul>
            </dd>
            <dt><?= $this->escape($translatePosts->translate("model")); ?></dt>
            <dd>
                <ul>
                    <?php
                    if (isset($facets["model"]["terms"])) {
                        foreach ($facets["model"]["terms"] as $term) {
                            if (! isset($term["term"]) || ! is_string($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                                continue;
                            }
                            ?>
                            <li><a href="<?= $searchLink ?>?q=*&amp;model=<?= urlencode($term["term"]); ?>"><?= $this->escape($term["term"]); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                        }
                        ?>
                    <?php
                    }
                    ?>
                </ul>
            </dd>
            <dt>Localização</dt>
            <dd>
                <ul>
                    <?php
                    if (isset($facets["where"]["terms"])) {
                        foreach ($facets["where"]["terms"] as $term) {
                            if (! isset($term["term"]) || ! is_string($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                                continue;
                            }
                            ?>
                            <li><a href="<?= $searchLink ?>?q=*&amp;where=<?= urlencode($term["term"]); ?>"><?= $this->escape($term["term"]); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                        }
                        ?>
                    <?php
                    }
                    ?>
                </ul>
            </dd>
            <dt>Ano do modelo</dt>
            <dd>
                <ul>
                    <?php
                    if (isset($facets["year"]["terms"])) {
                        foreach ($facets["year"]["terms"] as $term) {
                            if (! isset($term["term"]) || ! is_int($term["term"]) || ! isset($term["count"]) || ! is_int($term["count"])) {
                                continue;
                            }
                            ?>
                            <li><a href="<?= $searchLink ?>?q=*&amp;year=<?= urlencode($term["term"]); ?>"><?= $this->escape($term["term"]); ?></a> (<?= $this->escape($term["count"]); ?>)</li>
                        <?php
                        }
                        ?>
                    <?php
                    }
                    ?>
                </ul>
            </dd>
        </dl>
    </div>
</div>