<?php
$this->headTitle("Busca");
?>
<div class="container">
    <div class="row">
        <div class="span12">
            <h1 class="hidden">Busca</h1>
            <form method="GET" action="/search" id="search-posts-form">
                <div class="visible-desktop">&nbsp;</div>
                <div class="row">
                    <div class="span6">
                        <div class="search-text-area">
                        <input id="search-text" type="text" placeholder="O que você procura?" maxlength="80" class="search-text span6" name="q" autocomplete="off" />
                        <input id="search-text-autocomplete" type="text" disabled="disabled" class="search-text-autocomplete span6" />
                        </div>
                        <div class="row hidden">
                            <div class="span5">
                                <input type="text" id="search-price-max" placeholder="R$ máximo" maxlength="16" class="span2" name="price-max" />
                                <input type="text" id="search-price-min" placeholder="R$ mínimo" maxlength="16" class="span2" name="price-min" />
                                <input type="text" name="make" placeholder="Marca" />
                                <input type="text" name="model" placeholder="Modelo" />
                                <input type="text" name="year" placeholder="Ano" />
                                <input type="text" name="where" placeholder="Localização" />
                                <label class="radio">
                                    <input type="radio" name="type" value="" checked="checked" /> todo tipo de veículo
                                </label>
                                <label class="radio">
                                    <input type="radio" name="type" value="car" /> carro
                                </label>
                                <label class="radio">
                                    <input type="radio" name="type" value="motorcycle" /> motocicleta
                                </label>
                                <label class="radio">
                                    <input type="radio" name="type" value="boat" /> embarcação
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="span4">
                        <button type="submit" class="btn">Buscar</button>
                        &nbsp;
                        <div class="btn-group" data-toggle="buttons-radio" id="posts-view-style">
                            <?php
                            if (! $this->postsViewStyleIsTable) {
                                echo '<button id="posts-view-style-thumbnail" class="btn active" data-view-style="thumbnail"><i class="icon-th"></i></button>
<button id="posts-view-style-table" class="btn" data-view-style="table"><i class="icon-th-list"></i></button>';
                            } else {
                                echo '<button id="posts-view-style-thumbnail" class="btn" data-view-style="thumbnail"><i class="icon-th"></i></button>
<button id="posts-view-style-table" class="btn active" data-view-style="table"><i class="icon-th-list"></i></button>';
                            }
                            ?>
                        </div><!-- end of .btn-group -->
                        <button id="facets-toggle" class="btn visible-phone pull-right" data-toggle="button"><i class="icon-filter"></i><span class="hidden"> Filtros</span></button>
                    </div>
                </div>
            </form>
        </div><!-- end of .span12 -->
    </div><!-- end of .row -->
    <div class="row">
        <div class="span12">
            <div id="search-results"></div>
        </div>
    </div>
</div><!-- end of .container -->