<?php
$this->headTitle("Ache o seu veículo aqui");

if ($this->indexContent) {
    echo $this->indexContent;
}
?>
<div class="container">
    <div class="row">
        <div class="span12">
            <h1 class="hidden">Busca</h1>
            <noscript>Não é possível realizar buscas com o JavaScript desabilitado.</noscript>
            <div id="search-results"></div>
        </div>
    </div>
</div><!-- end of .container -->