<?php
//should not use <?php echo var ?\> here or it will print it (wrong)
//don't know why...
if(APPLICATION_ENV == "production"):
?>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("<?php echo $config['services']['ganalytics']['tracker_id'] ?>");
pageTracker._trackPageview();
} catch(err) {}</script>
<?php endif;