<?php
/**
 * this is the exception page that is loaded in some cases where a
 * unrecoverable fatal error happens (i.e., database failure)
 */

?>
<!DOCTYPE html>
<html lang="en">
<head>
<title>Application error</title>
<meta charset="utf-8" />
</head>
<body>
<h1>Application error</h1>
<p>An Internal Server Error has occurred.</p>
<p>The error has been reported to our log system so we can fix it.</p>
</body>
</html>