<?php
// Layout configuration file
$registry = Zend_Registry::getInstance();
$auth = Zend_Auth::getInstance();
$request = Zend_Controller_Front::getInstance()->getRequest();

$config = $registry->get('config');

$this->headScript()->setAllowArbitraryAttributes(true);

$this->headMeta()->appendName('keywords', $config['keywords']);
$this->headMeta()->appendName('description', $config['description']);

$this->headTitle()->setSeparator(' – ');

$this->addJsParam("webroot", $config['webroot']);

$this->addJsParam("cdn", $config['cdn']);

$this->addJsParam("imagesCdn", $config['services']['S3']['picturesBucketAddress']);

$this->headLink()
->appendStylesheet($this->staticVersion("/vendor/bootstrap/css/bootstrap.css"))
->appendStylesheet($this->staticVersion("/vendor/bootstrap/css/bootstrap-responsive.css"))
->appendStylesheet($this->staticVersion("/stylesheets/style.css"))
;

if ($auth->hasIdentity()) {
    $this->addJsParam("selfUid", $auth->getIdentity());
}

if ($registry->isRegistered("signedUserInfo")) {
    $signedUserInfo = $registry->get("signedUserInfo");
}

if ($registry->isRegistered("globalHash")) {
    $this->addJsParam("globalAuthHash", $registry->get("globalHash"));
}

$this->headScript()->prependScript($this->getJsParams());

?>
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="shortcut icon" href="<?php echo $this->staticVersion("/favicon.ico"); ?>">
<link href="<?php echo $this->staticVersion("/images/apple-touch-icon.png"); ?>" rel="apple-touch-icon" />
<?php
echo $this->headTitle() , PHP_EOL , 
$this->headLink() , PHP_EOL ,
$this->headMeta() , PHP_EOL;
?>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, user-scalable=no">
<?php echo $this->headScript(); ?>
<?php echo $this->headStyle(); ?>
<?php
/* Modernizr should load just after CSS */
?>
<script src="<?php echo $this->staticVersion("/vendor/modernizr/modernizr.js"); ?>"></script>
</head>
<body id="body">
<div class="site-logotype" id="site-logotype">
<a href="<?php echo $this->url(array(), "index"); ?>">
<img src="<?php echo $this->staticVersion("/images/logotype.png"); ?>" width="551" height="65" alt="<?= $this->escape($config["applicationname"]); ?>" /></a>
</div>
<div id="sticky-anchor"></div>
<div class="navbar navbar-inverse navbar-fixed-top navbar-fixed-top-override" id="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<?php echo $this->url(array(), "index"); ?>"><?php echo $this->escape($config['applicationname']); ?></a>
      <div class="nav-collapse">
        <ul class="nav">
            <li class="divider-vertical"></li>
            <li>
                <a href="<?= $this->url(array(), "user_post_new"); ?>" id="post-new-ad-button">
                    <i class="icon-pencil icon-white"></i> Anunciar
                </a>
            </li>
            <li class="divider-vertical"></li>
        </ul>
        <form class="navbar-search form-inline pull-left" action="<?= $this->url(array(), "search"); ?>" method="get">
          <label for="search-query"><i class="icon-white icon-search"></i>&nbsp;</label>
          <input type="text" id="search-query" class="search-query" placeholder="O que você procura?" name="q" />
        </form>
        <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <?php
            if (isset($signedUserInfo)) {
?>
        <li id="navbar-user" class="dropdown">
            <a href="<?php
                echo $this->url(array("username" => $signedUserInfo['username']), "user_stream_1stpage");
                ?>" data-target="#" class="dropdown-toggle" data-toggle="dropdown">
                <?php echo $this->avatar($signedUserInfo, "square.jpg", 20, 20); ?> <?php echo $this->escape($signedUserInfo['username']) ?>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="<?= $this->url(array("username" => $signedUserInfo['username']), "user_stream_1stpage"); ?>">Meus anúncios</a></li>
                <li><a href="<?= $this->url(array(), "account"); ?>">Minha conta</a></li>
                <li class="divider"></li>
                <li><a href="<?= $this->url(array(), "logout"); ?>" id="navbar-logout-link" rel="nofollow" class="navbar-logout-link">Sair</a></li>
            </ul>
        </li>
<?php
} else {
?>
                <li id="navbar-user" class="dropdown">
                    <a href="<?php echo $this->url(array(), "login") ?>" data-target="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-user icon-white"></i> Entrar
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <form class="navbar-login-well" enctype="application/x-www-form-urlencoded" action="<?= $this->url(array(), "login"); ?>" method="post">
                                <label for="navbar-login-username">Usuário ou email</label>
                                <input type="text" id="navbar-login-username" name="username" required="required">
                                <label for="navbar-login-password">Senha</label>
                                <input type="password" id="navbar-login-password" name="password" required="required">
                                <fieldset class="form-inline">
                                    <input type="hidden" name="remember_me" value="0" />
                                    <label class="checkbox">
                                        <input type="checkbox" name="remember_me" value="1" /> Relembrar-me
                                    </label>
                                    <button type="submit" class="btn">Entrar</button>
                                </fieldset>
                            </form>
                        </li>
                        <li><a href="<?php echo $this->url(array(), "recover") ?>">Perdeu seu usuário ou senha?</a></li>
                        <li><a href="<?php echo $this->url(array(), "join"); ?>">Cadastre-se</a></li>
                    </ul>
                </li>
<?php
}
?>
        </ul>
      </div>
    </div>
  </div>
</div><!-- end of navbar -->
<?= $this->render("messenger.phtml"); ?>
<?php echo $this->layout()->content; ?>
<footer class="footer">
<div class="container">
  <div class="row">
    <div class="span3 hidden-phone">
      <p><a href="http://www.twitter.com/<?php
      echo $this->escape($config['services']['twitter']['username']); ?>" class="new-window"><img src="<?php
echo $this->staticVersion("/images/follow_bird_us-b.png");
?>" alt="Follow us on Twitter" /></a></p>
    </div><!-- end of div -->
    <div class="span9">
        <ul class="nav nav-pills">
            <li><a href="<?php echo $this->url(array(), "index"); ?>">Página inicial</a></li>
            <li><a href="<?php echo $this->staticUrl("/about") ?>">Sobre</a></li>
            <li><a href="<?php echo $this->url(array(), "account"); ?>">Sua conta</a></li>
            <li><a href="<?php echo $this->staticUrl("/help") ?>">Suporte</a></li>
            <li><a href="<?php echo $this->staticUrl("/tos") ?>">Termos de Serviço</a></li>
            <li><a href="<?php echo $this->staticUrl("/privacy") ?>">Política de Privacidade</a></li>
        </ul>
    </div>
  </div><!-- end of div.row -->
</div>
</footer>
<?php
if (APPLICATION_ENV != "development") {
?>
<script>

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<?php echo $config['services']['ganalytics']['tracker_id']; ?>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<?php } ?>
<script data-main="<?php
echo $this->staticVersion("/javascripts/main.js");
?>" src="<?php echo $this->staticVersion("/vendor/require/require.js"); ?>"></script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>
