<?php
// Layout configuration file
$registry = Zend_Registry::getInstance();
$auth = Zend_Auth::getInstance();
$request = Zend_Controller_Front::getInstance()->getRequest();
$config = $registry->get('config');

$this->headScript()->setAllowArbitraryAttributes(true);

$this->headMeta()->appendName('keywords', $config['keywords']);
$this->headMeta()->appendName('description', $config['description']);

$this->headTitle()->setSeparator(' – ');

$this->addJsVar("webroot", $config['webroot']);

$this->headScript()->prependScript($this->getJsVarsText());

$this->headLink()
->appendStylesheet($this->staticVersion("/vendor/bootstrap/css/bootstrap.css"))
->appendStylesheet($this->staticVersion("/vendor/bootstrap/css/bootstrap-responsive.css"))
->appendStylesheet($this->staticVersion("/stylesheets/style.css"))
;

if ($auth->hasIdentity()) {
    $this->addJsVar("uid", $auth->getIdentity());
}

if ($registry->isRegistered("signedUserInfo")) {
    $signedUserInfo = $registry->get("signedUserInfo");
}

if ($registry->isRegistered("globalHash")) {
    $this->addJsVar("global_auth_hash", $registry->get("globalHash"));
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="shortcut icon" href="<?php echo $this->staticVersion("/favicon.ico"); ?>">
<link href="<?php echo $this->staticVersion("/images/apple-touch-icon.png"); ?>" rel="apple-touch-icon" />
<?php
echo $this->headTitle() , PHP_EOL , 
$this->headLink() , PHP_EOL ,
$this->headMeta() , PHP_EOL;
?>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, user-scalable=no">
<?php echo $this->headScript(); ?>
<?php echo $this->headStyle(); ?>
<?php
/* Modernizr should load just after CSS */
?>
<script src="<?php echo $this->staticVersion("/vendor/modernizr/modernizr.js"); ?>"></script>
</head>
<body>
<div class="site-logotype">
<a href="<?php echo $this->url(array(), "index"); ?>">
<img src="<?php echo $this->staticVersion("/images/logotype.png"); ?>" width="551" height="65" /></a>
</div>
<div id="sticky-anchor"></div>
<div class="navbar navbar-fixed-top navbar-fixed-top-override" id="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<?php echo $this->url(array(), "index"); ?>"><?php echo $this->escape($config['applicationname']); ?></a>
      <div class="nav-collapse">
        <ul class="nav">
            <li class="divider-vertical"></li>
<?php
echo $this->liMenuItems(
    array(
        array("route" => "ad_new", "name" => '<i class="icon-pencil icon-white"></i> Anunciar', "escape" => false)
    )
);
?>
            <li class="divider-vertical"></li>
        </ul>
        <form class="navbar-search form-inline pull-left" action="http://www.google.com/search" method="get">
          <label for="search-query"><i class="icon-white icon-search"></i>&nbsp;</label>
          <input type="text" id="search-query" class="search-query" placeholder="Search" name="q" />
          <input type="hidden" name="as_sitesearch" value="<?php echo $this->escape($config['webhost']); ?>" />
        </form>
        <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <?php
            if (isset($signedUserInfo)) {
?>
        <li class="dropdown">
            <a href="#"
               class="dropdown-toggle"
               data-toggle="dropdown">
                <?php echo $this->avatar($signedUserInfo, "square", false, array("width" => "20", "height" => "20")); ?> <?php echo $this->escape($signedUserInfo['alias']) ?>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                    <?php
                    echo $this->liMenuItems(
                        array(
                            array("route" => "profile", "name" => "Abrir perfil", "params" => array("username" => $signedUserInfo['alias'])),
                            array("route" => "filestream_1stpage", "name" => "Lista de veículos", "params" => array("username" => $signedUserInfo['alias'])),
                            array("route" => "account", "name" => "Sua conta")
                        )
                    );
                    ?>
                <li class="divider"></li>
                <?php
                echo $this->liMenuItems(
                    array(
                        array("route" => "logout", "name" => "Sair", "id" => "logout-link", "class" => "navbar-logout-link", "rel" => "nofollow", "escape" => false),
                    )
                );
                ?>
            </ul>
        </li>
<?php
} else {
    ?>
<?php
echo $this->liMenuItems(
    array(
        array("route" => "login", "name" => '<i class="icon-user icon-white"></i> Entrar', "escape" => false, "id" => "login-button")
    )
);
}
?>
        </ul>
      </div>
    </div>
  </div>
</div><!-- end of navbar -->
<?php
if ($registry->isRegistered("userInfo")) {
    echo $this->render("usermenu.phtml");
}
?>
<?php echo $this->layout()->content; ?>
<footer>
<div class="container">
  <div class="row">
    <div class="span6 visible-desktop">
      <p>Anuncie o seu carro no trazqueeupago.com você também.<br />
      <a href="http://www.twitter.com/<?php
      echo $this->escape($config['services']['twitter']['username']); ?>" class="new-window"><img src="<?php
echo $this->staticVersion("/images/follow_bird_us-b.png");
?>" alt="Follow us on Twitter" /></a></p>
    </div><!-- end of div -->
    <div class="span3">
      <ul>
        <li><a href="<?php echo $this->url(array(), "index"); ?>">Página inicial</a></li>
        <li><a href="<?php echo $this->url(array(), "account"); ?>">Sua conta</a></li>
        <li><a href="<?php echo $this->staticUrl("/about") ?>">Sobre</a></li>
      </ul>
    </div>
    <div class="span3">
      <ul>
        <li><a href="<?php echo $this->staticUrl("/tos") ?>">Termos de Serviço</a></li>
        <li><a href="<?php echo $this->staticUrl("/privacy") ?>">Política de Privacidade</a></li>
        <li><a href="<?php echo $this->staticUrl("/api") ?>">API</a></li>
        <li><a href="<?php echo $this->staticUrl("/help") ?>">Suporte</a></li>
      </ul>
    </div>
  </div><!-- end of div.row -->
</div>
</footer>
<?php
if (APPLICATION_ENV != "development") {
?>
<script>

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<?php echo $config['services']['ganalytics']['tracker_id']; ?>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<?php } ?>
<script src="<?php echo $this->staticVersion("/vendor/jquery/jquery.js"); ?>"></script>
<script src="<?php echo $this->staticVersion("/vendor/bootstrap/js/bootstrap.js"); ?>"></script>
<script src="<?php echo $this->staticVersion("/vendor/jquery-tablesorter/jquery.tablesorter.js"); ?>"></script>
<script src="<?php echo $this->staticVersion("/vendor/jquery-fn-autoResize/jquery.autoresize.js"); ?>"></script>
<script src="<?php echo $this->staticVersion("/javascripts/vehikel.js"); ?>"></script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>
