<?php
// Layout configuration file
$registry = Zend_Registry::getInstance();
$auth = Zend_Auth::getInstance();
$request = Zend_Controller_Front::getInstance()->getRequest();

$config = $registry->get('config');

$metaOgp = $this->metaOgp;

$metaOgp[] = ["property" => "og:locale", "content" => "pt_BR"];
$metaOgp[] = ["property" => "og:site_name", "content" => $this->escape($config["applicationname"])];
$metaOgp[] = ["property" => "og:image", "content" => $this->escape($this->staticVersion("/images/logotype.png"))];
$metaOgp[] = ["property" => "fb:admins", "content" => $this->escape($config["services"]["facebook"]["admins"])];

$this->headScript()->setAllowArbitraryAttributes(true);

$this->headMeta()->appendName('keywords', $config['keywords']);
$this->headMeta()->appendName('description', $config['description']);

$this->headTitle()->setSeparator(' – ');

$this->addJsParam("applicationname", $config['applicationname']);

$this->addJsParam("webroot", $config['webroot']);

$this->addJsParam("cdn", $config['cdn']);

$this->addJsParam("imagesCdn", $config['services']['thumbor']['cdn']);

$this->headLink()
->appendStylesheet($this->staticVersion("/vendor/bootstrap/css/bootstrap.css"))
->appendStylesheet($this->staticVersion("/vendor/bootstrap/css/bootstrap-responsive.css"))
->appendStylesheet($this->staticVersion("/stylesheets/style.css"))
;

if ($auth->hasIdentity()) {
    $this->addJsParam("selfUid", $auth->getIdentity());
}

if ($registry->isRegistered("signedUserInfo")) {
    $signedUserInfo = $registry->get("signedUserInfo");
}

if ($registry->isRegistered("globalHash")) {
    $this->addJsParam("globalAuthHash", $registry->get("globalHash"));
}

$this->headScript()->prependScript($this->getJsParams());

?>
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="shortcut icon" href="<?php echo $this->staticVersion("/favicon.ico"); ?>">
<link href="<?php echo $this->staticVersion("/images/apple-touch-icon.png"); ?>" rel="apple-touch-icon" />
<?php
echo $this->headTitle() , PHP_EOL , 
$this->headLink() , PHP_EOL ,
$this->headMeta() , PHP_EOL;
?>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, user-scalable=no">
<?php echo $this->headScript(); ?>
<?php echo $this->headStyle(); ?>
<?php
if (is_array($metaOgp)) {

    foreach ($metaOgp as $eachOg) {
?>
<meta property="<?= $this->escape($eachOg["property"]); ?>" content="<?= $this->escape($eachOg["content"]); ?>" />
<?php
    }
    unset($eachOg);
}

/* Modernizr should load just after CSS */
?>
<script src="<?php echo $this->staticVersion("/vendor/modernizr/modernizr.js"); ?>"></script>
</head>
<body id="body">
<div class="containers-not-on-bottom">
<div class="container navbar-container">
<div class="row site-topbar-row">
<div class="span3">
    <div class="site-logotype" id="site-logotype">
        <a href="<?php echo $this->url(array(), "index"); ?>">
            <img src="<?php echo $this->staticVersion("/images/logotype.png"); ?>" width="220" height="26" alt="<?= $this->escape($config["applicationname"]); ?>" /></a>
    </div>
</div><!-- end of .span3 -->
<?= $this->render("navbar.phtml"); ?>
</div><!-- end of .row -->
</div><!-- end of .container -->
<?= $this->render("messenger.phtml"); ?>
<div class="main-container-area">
<?php echo $this->layout()->content; ?>
</div><!-- end of .main-container-area -->
<div class="containers-on-bottom">
<footer class="footer">
<div class="container">
  <div class="row">
    <div class="span3 hidden-phone">
      <p><a href="http://www.twitter.com/<?php
      echo $this->escape($config['services']['twitter']['username']); ?>" class="new-window"><img src="<?php
echo $this->staticVersion("/images/follow_bird_us-b.png");
?>" alt="Follow us on Twitter" /></a></p>
    </div><!-- end of div -->
    <div class="span9">
        <ul class="nav nav-pills">
            <li><a href="<?php echo $this->url(array(), "index"); ?>">Página inicial</a></li>
            <li><a href="<?php echo $this->staticUrl("/about") ?>">Sobre</a></li>
            <li><a href="<?php echo $this->url(array(), "account"); ?>">Sua conta</a></li>
            <li><a href="<?php echo $this->staticUrl("/help") ?>">Suporte</a></li>
            <li><a href="<?php echo $this->staticUrl("/tos") ?>">Termos de Serviço</a></li>
            <li><a href="<?php echo $this->staticUrl("/privacy") ?>">Política de Privacidade</a></li>
        </ul>
    </div>
  </div><!-- end of div.row -->
</div>
</footer>
</div>
</div><!-- .containers-on-bottom -->
<?php
if (APPLICATION_ENV != "development") {
?>
<script>

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<?php echo $config['services']['ganalytics']['tracker_id']; ?>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<?php } ?>
<script data-main="<?php
echo $this->staticVersion("/javascripts/main.js");
?>" src="<?php echo $this->staticVersion("/vendor/require/require.js"); ?>"></script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>
