parameters:

    logger.adapter.mongo.collection: log
    logger.adapter.mongo.db: vehikel
services:
    mongo:
        class: Mongo
    purifier:
        class: Ml_Model_HtmlPurifier
    signup:
        class: Ml_Model_SignUp
        arguments: [@memCache]
    emailChange:
        class: Ml_Model_EmailChange
        arguments: [@memCache]
    picture:
        class: Ml_Model_Picture
        arguments: [@config]
    credential:
        class: Ml_Model_Credential
    recover:
        class: Ml_Model_Recover
        arguments: [@memCache]
    loggerAdapterMongo:
        class: Ml_Logger_Adapter_Mongo
        arguments: [%logger.adapter.mongo.collection%, %logger.adapter.mongo.db%, @Mongo, @zendAuth]
    logger:
        class: Ml_Logger
        arguments: [@loggerAdapterMongo, @zendAuth]
    session:
        class: Ml_Model_Session
        arguments: [@zendAuth , @memCache]
    loginForm:
        class: Ml_Form_Login
        arguments: [null, @config]
    logoutForm:
        class: Ml_Form_Logout
    recoverForm:
        class: Ml_Form_Recover
        arguments: [null, @people]
