parameters:

    logger.adapter.mongo.collection: log
    logger.adapter.mongo.db: vehikel
services:
    mongo:
        class: Mongo
    signup:
        class: Ml_Model_SignUp
        arguments: [@memCache]
    credential:
        class: Ml_Model_Credential
    loggerAdapterMongo:
        class: Ml_Logger_Adapter_Mongo
        arguments: [%logger.adapter.mongo.collection%, %logger.adapter.mongo.db%, @Mongo, @zendAuth]
    logger:
        class: Ml_Logger
        arguments: [@loggerAdapterMongo, @zendAuth]
    session:
        class: Ml_Model_Session
        arguments: [@zendAuth , @memCache]
