parameters:
    logger.adapter.mongo.collection: log
    logger.adapter.mongo.db: vehikel
services:
    http:
        class: Ml_Http
    mongo:
        class: Mongo
    numbers:
        class: Ml_Model_Numbers
    purifier:
        class: Ml_Model_HtmlPurifier
    signup:
        class: Ml_Model_SignUp
        arguments: [@memCache]
    emailChange:
        class: Ml_Model_EmailChange
        arguments: [@memCache]
    people:
        class: Ml_Model_People
        arguments: [null, @purifier, @picture, @gearmanClient]
    posts:
        class: Ml_Model_Posts
        arguments: [null, @gearmanClient, @people, @purifier, @numbers, @picture]
    picture:
        class: Ml_Model_Picture
        arguments: [null, @http, @config]
    search:
        class: Ml_Model_Search
        arguments: [@people, @posts, @memCache, @config]
    typeaheadMakes:
        class: Ml_Model_TypeaheadMakes
        arguments: [null, @memCache]
    typeaheadModels:
        class: Ml_Model_TypeaheadModels
        arguments: [null, @memCache]
    credential:
        class: Ml_Model_Credential
    recover:
        class: Ml_Model_Recover
        arguments: [@memCache]
    contactSeller:
        class: Ml_Model_ContactSeller
        arguments: [null]
    loggerAdapterMongo:
        class: Ml_Logger_Adapter_Mongo
        arguments: [%logger.adapter.mongo.collection%, %logger.adapter.mongo.db%, @Mongo, @zendAuth]
    loggerAdapterZendDb:
        class: Ml_Logger_Adapter_ZendDb
        arguments: [null]
    logger:
        class: Ml_Logger
        arguments: [@loggerAdapterZendDb, @zendAuth]
    session:
        class: Ml_Model_Session
        arguments: [@zendAuth , @memCache]
    gearmanClient:
        class: GearmanClient
        calls:
            - [ addServers ]
    account:
        class: Ml_Model_Account
        arguments: [@people, @gearmanClient]
    newsletter_manager:
        class:     NewsletterManager
        calls:
            - [ setMailer, [ @mailer ] ]