<?php
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");
$this->headTitle("Continue o seu cadastro em " . $config['applicationname'], "SET");
$this->confirmForm->getElement("password")->getDecorator("description")->setEscape(false);

$form = $this->confirmForm;
/** @var $form \Ml_Form_NewIdentity() */

?>
&nbsp;
<div class="container">
    <div class="row">
        <div class="span12">
            <h1>Cadastro</h1>
            <form enctype="application/x-www-form-urlencoded" action="<?= $form->getAction(); ?>" class="form-stacked" method="post">
            <?php
                echo $form->name, $form->email, $form->newusername, $form->password, $form->password_confirm;

                $tosElement = $form->getElement("tos");
                $tosErrors = $tosElement->getErrors();
            ?>
                <div class="control-group<?= (empty($tosErrors)) ? "" : " error"; ?>">
                    <div class="controls">
                        <label class="checkbox inline">
                        <input type="hidden" name="tos" value="0" />
                        <input type="checkbox" name="tos" id="tos" value="agree"
                            <?php
                                if ($tosElement->getValue() == "agree") {
                                    echo ' checked="checked" ';
                                }
                            ?>
                        />
                        Eu concordo com os Termos de Serviço
                        </label>&nbsp;<small> <a href="/tos" title="Termos de Serviço" rel="external">(abrir)</a></small>
                        <?php
                            if (! empty($tosError)) {
                        ?>
                        <span class="help-block">Você deve concordar com os Termos de Serviço para poder continuar.</span>
                        <?php
                            }
                        ?>
                    </div>
                </div>
                <div class="form-actions">
                    <input type="submit" name="submit" id="submit" value="Confirmar cadastro" class="btn btn-primary btn-large" />
                </div>
                <?php
                    echo $form->no_csrf_foo;
                ?>
            </form>
        </div>
    </div><!-- end of .row -->
</div><!-- end of .container -->