<?php
$config = Zend_Registry::getInstance()->get('config');
?>
Hi <?php echo $this->escape($this->entry['name']) ?>!

Welcome to <?php echo $this->escape($config['applicationname']); ?>.

Please confirm your e-mail address at
<?php

if ($config['ssl']) {
    echo "https://" . $config['webhostssl'];
} else {
    echo "http://" . $config['webhost'];
}

echo $this->url(array("security_code" => $this->entry['securitycode']), "join_emailconfirm");
?>


Terms of Service - http://<?php echo $this->escape($config['webhost']) ?><?php echo $this->staticUrl("/tos") ?>
Privacy Policy - http://<?php echo $this->escape($config['webhost']) ?><?php echo $this->staticUrl("/privacy") ?>

-
<?php echo $this->escape($config['applicationname']); ?>
<?php echo $this->escape($config['webhost']);