<?php $config = Zend_Registry::getInstance()->get('config'); ?>
Hi <?= $this->escape($this->entry['name']) ?>!

Welcome to Plifk.

Please confirm your e-mail address at
<?= ($config['ssl']) ? "https://" . $config['webhostssl'] : "http://" . $config['webhost'] ?><?= $this->url(array("security_code" => $this->entry['securitycode']), "join_emailconfirm") ?>


Terms of Service - http://<?= $this->escape($config['webhost']) ?><?= $this->staticUrl("/tos") ?>
Privacy Policy - http://<?= $this->escape($config['webhost']) ?><?= $this->staticUrl("/privacy") ?>

-
<?= $this->escape($config['applicationname']) ?>
<?= $this->escape($config['webhost']) ?>