<?php
$config = Zend_Registry::getInstance()->get('config');
?>
Olá <?php echo $this->escape($this->newUserInfo['name']) ?>!

Bem vindo ao <?php echo $this->escape($config['applicationname']); ?>.

Para continuar o seu cadastro por favor confirme o seu endereço de email em:
<?php

if ($config['ssl']) {
    echo "https://" . $config['webhostssl'];
} else {
    echo "http://" . $config['webhost'];
}

echo $this->url(array("security_code" => $this->newUserInfo['securitycode']), "join_emailconfirm");
?>


Política de privacidade - http://<?php echo $this->escape($config['webhost']) ?><?php echo $this->staticUrl("/privacy") ?>


-
<?php
echo $this->escape($config['applicationname']) . "\n"
. $this->escape($config['webhost']);