<?php
$this->headTitle("Não foi possível confirmar o seu email");
?>
&nbsp;
<div class="container">
    <div class="row">
        <div class="span12">
            <h1>Não foi possível confirmar o seu email</h1>
            <p>Provavelmente você já possui um cadastro ou esse link de confirmação expirou.<br /><br />
            <a href="<?php echo $this->url(array(), "join"); ?>" class="btn">Tentar iniciar o cadastro novamente</a></p>
        </div>
    </div><!-- end of .row -->
</div><!-- end of .container -->