<?php
$registry = Zend_Registry::getInstance();
$signedUserInfo = $registry->get("signedUserInfo");

$config = $registry->get('config');

$this->headTitle("Welcome to " . $config['applicationname'] . ", " .
 $this->escape($signedUserInfo['name']) . "!", "SET");
?>
<div class="row">
<div class="span16">
<h2>Welcome <?php echo $this->escape($signedUserInfo['name']); ?>!</h2>
<p><b>Your username is <?php
echo $this->escape($signedUserInfo['alias']);
?></b>. You're signed in and can <a href="<?php
echo $this->url(array(), "upload");
?>" rel="nofollow">start uploading files</a>.<br /><br />
<b>Do you use Twitter?</b> <a href="<?php
echo $this->url(array(), "accounttwitter");
?>">Connect Plifk to your Twitter account now!</a><br /><br />
<b>People can find you at </b> <a href="http://www.plifk.com<?php
echo $this->url(array("username" => $signedUserInfo['alias']), "filestream_1stpage");
?>">http://www.plifk.com<?php
echo $this->url(array("username" => $signedUserInfo['alias']), "filestream_1stpage");
?></a><br /><br />
We hope you enjoy Plifk!</p>
</div>
</div>