<?php
$registry = Zend_Registry::getInstance();
$config = $registry->get("config");
$this->headTitle("Complete o seu cadastro");

$signedUserInfo = $registry->get("signedUserInfo");
?>
&nbsp;
<div class="container">
    <div class="row">
        <div class="span12">
            <h1>Bem vindo, <?php echo $this->escape($signedUserInfo['name']); ?>!</h1>
            <p>
                <strong>As pessoas podem encontrar você em:</strong><br />
                <?php
                echo '<a href="http://', $config["webhost"],
                $this->url(array("username" => $signedUserInfo['username']), "user_stream_1stpage"), '">',
                "http://", $config["webhost"],
                $this->url(array("username" => $signedUserInfo['username']), "user_stream_1stpage"), '</a>';
                ?>
            </p>
            <?php
            if (! $signedUserInfo["avatar_info"] || ! $signedUserInfo["address"]) {
            ?>
            <div class="alert alert-info">
                <p>Para poder anunciar está faltando você:
                <ul>
                <?php
                if (! $signedUserInfo["avatar_info"]) {
                ?>
                    <li><a href="<?= $this->url(array(), "account_picture"); ?>">Colocar uma imagem de perfil</a></li>
                <?php
                }
                if (! $signedUserInfo["address"]) {
                ?>
                    <li><a href="<?= $this->url(array(), "account_address"); ?>">Configurar o seu endereço</a></li>
                <?php
                }
                ?>
                </ul>
                </p>
            </div>
            <?php
            }
            ?>
            <p><a class="btn btn-large" href="<?= $this->url(array(), "account"); ?>">
                <i class="icon-arrow-right"></i> Configurar a sua conta
            </a>
            <?php
                if ($signedUserInfo["avatar_info"] && $signedUserInfo["address"]) {
            ?>
            &nbsp;&nbsp;&nbsp;
                <a class="btn btn-large" href="<?= $this->url(array(), "ad_new"); ?>">
                    <i class="icon-arrow-right"></i> Anunciar
                </a>
            <?php
                }
            ?>
            </p>
        </div>
    </div><!-- end of .row -->
</div><!-- end of .container -->