<?php
$this->headTitle("HTML formatting");
?>
<h2>HTML formatting</h2>
<p>You can use the following mark-up on your about, descriptions and comments.</p>
<table class="styled">
<thead><tr><th><acronym title="HyperText Markup Language">HTML</acronym> Tag</th><th>Attributes</th></tr></thead>
<tbody>
<tr>
<td class="left">&lt;a href="<em>URL</em>"&gt;<a href="#">link</a>&lt;/a&gt;</td>
<td>'href', 'title'</td></tr>
<tr>
<td class="left">&lt;strong&gt;<strong>strong</strong>&lt;/strong&gt;</td>
<td></td>
</tr>
<tr>
<td class="left">&lt;b&gt;<b>bold</b>&lt;/b&gt;</td>
<td></td>
</tr><?php
/*<tr>
<td>&lt;blockquote&gt;<blockquote><ins>blockquote</ins></blockquote>&lt;/blockquote&gt;</td>
<td></td>
</tr>*/
?>
<tr>
<td class="left">&lt;em&gt;<em>emphasis</em>&lt;/em&gt;</td>
<td></td>
</tr>
<tr>
<td class="left">&lt;i&gt;<i>italic</i>&lt;/i&gt;</td>
<td></td>
</tr>
<tr>
<td class="left">&lt;img src="<em>URL</em>" /&gt;</td>
<td>'src', 'width', 'height', 'alt', 'title'</td></tr>
<tr>
<td class="somehtml left">&lt;ins&gt;<ins>ins</ins>&lt;/ins&gt;</td>
<td></td>
</tr>
<tr>
<td class="left">&lt;del&gt;<del>deleted</del>&lt;/del&gt;</td>
<td></td>
</tr>
</tbody>
</table>
<p>Each HTML Tag above is intended for something distinct (even when it looks the same), read this <a href="http://xhtml.com/en/xhtml/reference/" class="new-window" title="Extensible HyperText Markup Language Reference">XHTML Reference</a> to understand them.</p>